/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.private_get_deposits_request_currency as enum (
    'BTC',
    'ETH',
    'EURR',
    'USDC',
    'USDT'
);

create type deribit.private_get_deposits_request as (
    "currency" deribit.private_get_deposits_request_currency,
    "count" bigint,
    "offset" bigint
);

comment on column deribit.private_get_deposits_request."currency" is '(Required) The currency symbol';
comment on column deribit.private_get_deposits_request."count" is 'Number of requested items, default - 10, maximum - 1000';
comment on column deribit.private_get_deposits_request."offset" is 'The offset for pagination, default - 0';

create type deribit.private_get_deposits_response_datum as (
    "address" text,
    "amount" double precision,
    "clearance_state" text,
    "currency" text,
    "note" text,
    "received_timestamp" bigint,
    "refund_transaction_id" text,
    "source_address" text,
    "state" text,
    "transaction_id" text,
    "updated_timestamp" bigint
);

comment on column deribit.private_get_deposits_response_datum."address" is 'Address in proper format for currency';
comment on column deribit.private_get_deposits_response_datum."amount" is 'Amount of funds in given currency';
comment on column deribit.private_get_deposits_response_datum."clearance_state" is 'Clearance state indicating the current status of the transaction clearance process. Allowed values: in_progress: clearance process is in progress pending_admin_decision: transaction is under manual review by Deribit admin pending_user_input: user should provide additional information regarding the transaction success: clearance process completed successfully failed: clearance process failed, transaction is rejected cancelled: transaction is cancelled (currently used only for withdrawals, meaning the withdrawal is cancelled) refund_initiated: clearance process failed, transaction refund is initiated, funds are removed from Deribit balance (valid for deposits only) refunded: clearance process failed, deposit amount is refunded back to the client (valid for deposits only)';
comment on column deribit.private_get_deposits_response_datum."currency" is 'Currency, i.e "BTC", "ETH", "USDC"';
comment on column deribit.private_get_deposits_response_datum."received_timestamp" is 'The timestamp (milliseconds since the Unix epoch)';
comment on column deribit.private_get_deposits_response_datum."refund_transaction_id" is 'Transaction id in proper format for currency, null if id is not available';
comment on column deribit.private_get_deposits_response_datum."source_address" is 'Address in proper format for currency';
comment on column deribit.private_get_deposits_response_datum."state" is 'Deposit state. Allowed values: pending: deposit detected on blockchain/system, compliance not yet finished completed: compliance check finished successfully rejected: deposit failed compliance and must be handled manually replaced: deposit transaction was replaced on the blockchain and should have a new transaction hash';
comment on column deribit.private_get_deposits_response_datum."transaction_id" is 'Transaction id in proper format for currency, null if id is not available';
comment on column deribit.private_get_deposits_response_datum."updated_timestamp" is 'The timestamp (milliseconds since the Unix epoch)';

create type deribit.private_get_deposits_response_result as (
    "count" bigint,
    "data" deribit.private_get_deposits_response_datum[]
);

comment on column deribit.private_get_deposits_response_result."count" is 'Total number of results available';

create type deribit.private_get_deposits_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" deribit.private_get_deposits_response_result
);

comment on column deribit.private_get_deposits_response."id" is 'The id that was sent in the request';
comment on column deribit.private_get_deposits_response."jsonrpc" is 'The JSON-RPC version (2.0)';

create function deribit.private_get_deposits(
    "currency" deribit.private_get_deposits_request_currency,
    "count" bigint default null,
    "offset" bigint default null
)
returns deribit.private_get_deposits_response_result
language sql
as $$
    
    with request as (
        select row(
            "currency",
            "count",
            "offset"
        )::deribit.private_get_deposits_request as payload
    ), 
    http_response as (
        select deribit.private_jsonrpc_request(
            auth := deribit.get_auth(),
            url := '/private/get_deposits'::deribit.endpoint,
            request := request.payload,
            rate_limiter := 'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
        from request
    )
    select (
        jsonb_populate_record(
            null::deribit.private_get_deposits_response,
            convert_from((a.http_response).body, 'utf-8')::jsonb
        )
    ).result
    from http_response a

$$;

comment on function deribit.private_get_deposits is 'Retrieve the latest users deposits';
