/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.private_get_mmp_config_request_index_name as enum (
    'ada_usdc',
    'algo_usdc',
    'all',
    'avax_usdc',
    'bch_usdc',
    'bnb_usdc',
    'btc_usd',
    'btc_usdc',
    'btc_usdt',
    'btcdvol_usdc',
    'buidl_usdc',
    'doge_usdc',
    'dot_usdc',
    'eth_usd',
    'eth_usdc',
    'eth_usdt',
    'ethdvol_usdc',
    'link_usdc',
    'ltc_usdc',
    'near_usdc',
    'paxg_usdc',
    'shib_usdc',
    'sol_usdc',
    'trump_usdc',
    'trx_usdc',
    'uni_usdc',
    'usde_usdc',
    'xrp_usdc'
);

create type deribit.private_get_mmp_config_request as (
    "index_name" deribit.private_get_mmp_config_request_index_name,
    "mmp_group" text,
    "block_rfq" boolean
);

comment on column deribit.private_get_mmp_config_request."index_name" is 'Index identifier of derivative instrument on the platform; skipping this parameter will return all configurations';
comment on column deribit.private_get_mmp_config_request."mmp_group" is 'Specifies the MMP group for which the configuration is being retrieved. MMP groups are used for Mass Quotes. If MMP group is not provided, the endpoint returns the configuration for the MMP settings for regular orders. The index_name must be specified before using this parameter';
comment on column deribit.private_get_mmp_config_request."block_rfq" is 'If true, retrieves MMP configuration for Block RFQ. When set, requires block_rfq scope instead of trade scope. Block RFQ MMP settings are completely separate from normal order/quote MMP settings.';

create type deribit.private_get_mmp_config_response_result as (
    "block_rfq" boolean,
    "delta_limit" double precision,
    "frozen_time" bigint,
    "index_name" text,
    "interval" bigint,
    "mmp_group" text,
    "quantity_limit" double precision,
    "trade_count_limit" bigint,
    "vega_limit" double precision
);

comment on column deribit.private_get_mmp_config_response_result."block_rfq" is 'If true, indicates MMP configuration for Block RFQ. Block RFQ MMP settings are completely separate from normal order/quote MMP settings.';
comment on column deribit.private_get_mmp_config_response_result."delta_limit" is 'Delta limit';
comment on column deribit.private_get_mmp_config_response_result."frozen_time" is 'MMP frozen time in seconds, if set to 0 manual reset is required';
comment on column deribit.private_get_mmp_config_response_result."index_name" is 'Index identifier, matches (base) cryptocurrency with quote currency';
comment on column deribit.private_get_mmp_config_response_result."interval" is 'MMP Interval in seconds, if set to 0 MMP is disabled';
comment on column deribit.private_get_mmp_config_response_result."mmp_group" is 'Specified MMP Group';
comment on column deribit.private_get_mmp_config_response_result."quantity_limit" is 'Quantity limit';
comment on column deribit.private_get_mmp_config_response_result."trade_count_limit" is 'For Block RFQ only. The maximum number of Block RFQ trades allowed in the lookback window. Each RFQ trade counts as +1 towards the limit (not individual legs). Works across all currency pairs.';
comment on column deribit.private_get_mmp_config_response_result."vega_limit" is 'Vega limit';

create type deribit.private_get_mmp_config_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" deribit.private_get_mmp_config_response_result[]
);

comment on column deribit.private_get_mmp_config_response."id" is 'The id that was sent in the request';
comment on column deribit.private_get_mmp_config_response."jsonrpc" is 'The JSON-RPC version (2.0)';

create function deribit.private_get_mmp_config(
    "index_name" deribit.private_get_mmp_config_request_index_name default null,
    "mmp_group" text default null,
    "block_rfq" boolean default null
)
returns setof deribit.private_get_mmp_config_response_result
language sql
as $$
    
    with request as (
        select row(
            "index_name",
            "mmp_group",
            "block_rfq"
        )::deribit.private_get_mmp_config_request as payload
    ), 
    http_response as (
        select deribit.private_jsonrpc_request(
            auth := deribit.get_auth(),
            url := '/private/get_mmp_config'::deribit.endpoint,
            request := request.payload,
            rate_limiter := 'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
        from request
    ),
    result as (
        select (jsonb_populate_record(
            null::deribit.private_get_mmp_config_response,
            convert_from((http_response.http_response).body, 'utf-8')::jsonb)
        ).result
        from http_response
    )
    select
        (b)."block_rfq"::boolean,
        (b)."delta_limit"::double precision,
        (b)."frozen_time"::bigint,
        (b)."index_name"::text,
        (b)."interval"::bigint,
        (b)."mmp_group"::text,
        (b)."quantity_limit"::double precision,
        (b)."trade_count_limit"::bigint,
        (b)."vega_limit"::double precision
    from (
        select (unnest(r.data)) b
        from result r(data)
    ) a
    
$$;

comment on function deribit.private_get_mmp_config is 'Get MMP configuration for an index, if the parameter is not provided, a list of all MMP configurations is returned. Empty list means no MMP configuration.';
