/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.private_list_address_beneficiaries_request_currency as enum (
    'BNB',
    'BTC',
    'ETH',
    'ETHW',
    'EURR',
    'MATIC',
    'PAXG',
    'SOL',
    'STETH',
    'USDC',
    'USDE',
    'USDT',
    'USYC',
    'XRP'
);

create type deribit.private_list_address_beneficiaries_request as (
    "currency" deribit.private_list_address_beneficiaries_request_currency,
    "address" text,
    "tag" text,
    "created_before" bigint,
    "created_after" bigint,
    "updated_before" bigint,
    "updated_after" bigint,
    "personal" boolean,
    "unhosted" boolean,
    "beneficiary_vasp_name" text,
    "beneficiary_vasp_did" text,
    "beneficiary_vasp_website" text,
    "limit" bigint,
    "continuation" text
);

comment on column deribit.private_list_address_beneficiaries_request."currency" is 'The currency symbol';
comment on column deribit.private_list_address_beneficiaries_request."address" is 'Address in currency format';
comment on column deribit.private_list_address_beneficiaries_request."tag" is 'Tag for XRP addresses';
comment on column deribit.private_list_address_beneficiaries_request."created_before" is 'Filter by creation timestamp (before)';
comment on column deribit.private_list_address_beneficiaries_request."created_after" is 'Filter by creation timestamp (after)';
comment on column deribit.private_list_address_beneficiaries_request."updated_before" is 'Filter by update timestamp (before)';
comment on column deribit.private_list_address_beneficiaries_request."updated_after" is 'Filter by update timestamp (after)';
comment on column deribit.private_list_address_beneficiaries_request."personal" is 'Filter by personal wallet flag';
comment on column deribit.private_list_address_beneficiaries_request."unhosted" is 'Filter by unhosted wallet flag';
comment on column deribit.private_list_address_beneficiaries_request."beneficiary_vasp_name" is 'Filter by beneficiary VASP name';
comment on column deribit.private_list_address_beneficiaries_request."beneficiary_vasp_did" is 'Filter by beneficiary VASP DID';
comment on column deribit.private_list_address_beneficiaries_request."beneficiary_vasp_website" is 'Website of the beneficiary VASP. Required if the address book entry is associated with a VASP that is not included in the list of known VASPs';
comment on column deribit.private_list_address_beneficiaries_request."limit" is 'Maximum number of results to return';
comment on column deribit.private_list_address_beneficiaries_request."continuation" is 'Continuation token for pagination';

create type deribit.private_list_address_beneficiaries_response_datum as (
    "address" text,
    "agreed" boolean,
    "beneficiary_address" text,
    "beneficiary_company_name" text,
    "beneficiary_first_name" text,
    "beneficiary_last_name" text,
    "beneficiary_vasp_did" text,
    "beneficiary_vasp_name" text,
    "beneficiary_vasp_website" text,
    "creation_timestamp" bigint,
    "currency" text,
    "personal" boolean,
    "tag" text,
    "unhosted" boolean,
    "update_timestamp" bigint
);

comment on column deribit.private_list_address_beneficiaries_response_datum."address" is 'Address in proper format for currency';
comment on column deribit.private_list_address_beneficiaries_response_datum."agreed" is 'Indicates that the user agreed to shared provided information with 3rd parties';
comment on column deribit.private_list_address_beneficiaries_response_datum."beneficiary_address" is 'Geographical address of the beneficiary';
comment on column deribit.private_list_address_beneficiaries_response_datum."beneficiary_company_name" is 'Company name of the beneficiary (if beneficiary is a company)';
comment on column deribit.private_list_address_beneficiaries_response_datum."beneficiary_first_name" is 'First name of the beneficiary (if beneficiary is a person)';
comment on column deribit.private_list_address_beneficiaries_response_datum."beneficiary_last_name" is 'Last name of the beneficiary (if beneficiary is a person)';
comment on column deribit.private_list_address_beneficiaries_response_datum."beneficiary_vasp_did" is 'DID of beneficiary VASP';
comment on column deribit.private_list_address_beneficiaries_response_datum."beneficiary_vasp_name" is 'Name of beneficiary VASP';
comment on column deribit.private_list_address_beneficiaries_response_datum."beneficiary_vasp_website" is 'Website of the beneficiary VASP';
comment on column deribit.private_list_address_beneficiaries_response_datum."creation_timestamp" is 'The timestamp (milliseconds since the Unix epoch)';
comment on column deribit.private_list_address_beneficiaries_response_datum."currency" is 'Currency, i.e "BTC", "ETH", "USDC"';
comment on column deribit.private_list_address_beneficiaries_response_datum."personal" is 'The user confirms that he provided address belongs to him and he has access to it via an un-hosted wallet software';
comment on column deribit.private_list_address_beneficiaries_response_datum."tag" is 'Tag for XRP addresses (optional)';
comment on column deribit.private_list_address_beneficiaries_response_datum."unhosted" is 'Indicates if the address belongs to an unhosted wallet';
comment on column deribit.private_list_address_beneficiaries_response_datum."update_timestamp" is 'The timestamp (milliseconds since the Unix epoch)';

create type deribit.private_list_address_beneficiaries_response_result as (
    "continuation" text,
    "count" bigint,
    "data" deribit.private_list_address_beneficiaries_response_datum[]
);

comment on column deribit.private_list_address_beneficiaries_response_result."continuation" is 'Continuation token for pagination.';
comment on column deribit.private_list_address_beneficiaries_response_result."count" is 'Total number of results available';

create type deribit.private_list_address_beneficiaries_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" deribit.private_list_address_beneficiaries_response_result
);

comment on column deribit.private_list_address_beneficiaries_response."id" is 'The id that was sent in the request';
comment on column deribit.private_list_address_beneficiaries_response."jsonrpc" is 'The JSON-RPC version (2.0)';

create function deribit.private_list_address_beneficiaries(
    "currency" deribit.private_list_address_beneficiaries_request_currency default null,
    "address" text default null,
    "tag" text default null,
    "created_before" bigint default null,
    "created_after" bigint default null,
    "updated_before" bigint default null,
    "updated_after" bigint default null,
    "personal" boolean default null,
    "unhosted" boolean default null,
    "beneficiary_vasp_name" text default null,
    "beneficiary_vasp_did" text default null,
    "beneficiary_vasp_website" text default null,
    "limit" bigint default null,
    "continuation" text default null
)
returns deribit.private_list_address_beneficiaries_response_result
language sql
as $$
    
    with request as (
        select row(
            "currency",
            "address",
            "tag",
            "created_before",
            "created_after",
            "updated_before",
            "updated_after",
            "personal",
            "unhosted",
            "beneficiary_vasp_name",
            "beneficiary_vasp_did",
            "beneficiary_vasp_website",
            "limit",
            "continuation"
        )::deribit.private_list_address_beneficiaries_request as payload
    ), 
    http_response as (
        select deribit.private_jsonrpc_request(
            auth := deribit.get_auth(),
            url := '/private/list_address_beneficiaries'::deribit.endpoint,
            request := request.payload,
            rate_limiter := 'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
        from request
    )
    select (
        jsonb_populate_record(
            null::deribit.private_list_address_beneficiaries_response,
            convert_from((a.http_response).body, 'utf-8')::jsonb
        )
    ).result
    from http_response a

$$;

comment on function deribit.private_list_address_beneficiaries is 'Lists address beneficiaries with optional filtering and pagination';
