/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.private_add_to_address_book_request_currency as enum (
    'BNB',
    'BTC',
    'ETH',
    'ETHW',
    'EURR',
    'MATIC',
    'PAXG',
    'SOL',
    'STETH',
    'USDC',
    'USDE',
    'USDT',
    'USYC',
    'XRP'
);

create type deribit.private_add_to_address_book_request_type as enum (
    'deposit_source',
    'transfer',
    'withdrawal'
);

create type deribit.private_add_to_address_book_request as (
    "currency" deribit.private_add_to_address_book_request_currency,
    "type" deribit.private_add_to_address_book_request_type,
    "address" text,
    "label" text,
    "beneficiary_vasp_name" text,
    "beneficiary_vasp_did" text,
    "beneficiary_first_name" text,
    "beneficiary_last_name" text,
    "beneficiary_company_name" text,
    "beneficiary_address" text,
    "agreed" boolean,
    "personal" boolean
);

comment on column deribit.private_add_to_address_book_request."currency" is '(Required) The currency symbol';
comment on column deribit.private_add_to_address_book_request."type" is '(Required) Address book type';
comment on column deribit.private_add_to_address_book_request."address" is '(Required) Address in currency format';
comment on column deribit.private_add_to_address_book_request."label" is '(Required) Label of the address book entry';
comment on column deribit.private_add_to_address_book_request."beneficiary_vasp_name" is '(Required) Name of beneficiary VASP';
comment on column deribit.private_add_to_address_book_request."beneficiary_vasp_did" is '(Required) DID of beneficiary VASP';
comment on column deribit.private_add_to_address_book_request."beneficiary_first_name" is 'First name of beneficiary (if beneficiary is a person)';
comment on column deribit.private_add_to_address_book_request."beneficiary_last_name" is 'First name of beneficiary (if beneficiary is a person)';
comment on column deribit.private_add_to_address_book_request."beneficiary_company_name" is 'Beneficiary company name (if beneficiary is a company)';
comment on column deribit.private_add_to_address_book_request."beneficiary_address" is '(Required) nan';
comment on column deribit.private_add_to_address_book_request."agreed" is '(Required) Indicates that the user agreed to shared provided information with 3rd parties';
comment on column deribit.private_add_to_address_book_request."personal" is '(Required) The user confirms that he provided address belongs to him and he has access to it via an un-hosted wallet software';

create type deribit.private_add_to_address_book_response_result as (
    "address" text,
    "agreed" boolean,
    "beneficiary_address" text,
    "beneficiary_company_name" text,
    "beneficiary_first_name" text,
    "beneficiary_last_name" text,
    "beneficiary_vasp_did" text,
    "beneficiary_vasp_name" text,
    "creation_timestamp" bigint,
    "currency" text,
    "info_required" boolean,
    "label" text,
    "personal" boolean,
    "requires_confirmation" boolean,
    "requires_confirmation_change" boolean,
    "status" text,
    "type" text,
    "waiting_timestamp" boolean
);

comment on column deribit.private_add_to_address_book_response_result."address" is 'Address in proper format for currency';
comment on column deribit.private_add_to_address_book_response_result."agreed" is 'Indicates that the user agreed to shared provided information with 3rd parties';
comment on column deribit.private_add_to_address_book_response_result."beneficiary_address" is 'Geographical address of the beneficiary';
comment on column deribit.private_add_to_address_book_response_result."beneficiary_first_name" is 'First name of the beneficiary (if beneficiary is a person)';
comment on column deribit.private_add_to_address_book_response_result."beneficiary_last_name" is 'Last name of the beneficiary (if beneficiary is a person)';
comment on column deribit.private_add_to_address_book_response_result."beneficiary_vasp_did" is 'DID of beneficiary VASP';
comment on column deribit.private_add_to_address_book_response_result."beneficiary_vasp_name" is 'Name of beneficiary VASP';
comment on column deribit.private_add_to_address_book_response_result."creation_timestamp" is 'The timestamp (milliseconds since the Unix epoch)';
comment on column deribit.private_add_to_address_book_response_result."currency" is 'Currency, i.e "BTC", "ETH", "USDC"';
comment on column deribit.private_add_to_address_book_response_result."info_required" is 'Signalises that addition information regarding the beneficiary of the address is required';
comment on column deribit.private_add_to_address_book_response_result."label" is 'Label of the address book entry';
comment on column deribit.private_add_to_address_book_response_result."personal" is 'The user confirms that he provided address belongs to him and he has access to it via an un-hosted wallet software';
comment on column deribit.private_add_to_address_book_response_result."requires_confirmation" is 'If address requires email confirmation for withdrawals';
comment on column deribit.private_add_to_address_book_response_result."requires_confirmation_change" is 'If email confirmation change is in progress';
comment on column deribit.private_add_to_address_book_response_result."status" is 'Wallet address status, values: [admin_locked, waiting, confirmed, ready]';
comment on column deribit.private_add_to_address_book_response_result."type" is 'Address book type';
comment on column deribit.private_add_to_address_book_response_result."waiting_timestamp" is 'Timestamp when the address will be ready';

create type deribit.private_add_to_address_book_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" deribit.private_add_to_address_book_response_result
);

comment on column deribit.private_add_to_address_book_response."id" is 'The id that was sent in the request';
comment on column deribit.private_add_to_address_book_response."jsonrpc" is 'The JSON-RPC version (2.0)';

create function deribit.private_add_to_address_book(
    "currency" deribit.private_add_to_address_book_request_currency,
    "type" deribit.private_add_to_address_book_request_type,
    "address" text,
    "label" text,
    "beneficiary_vasp_name" text,
    "beneficiary_vasp_did" text,
    "beneficiary_address" text,
    "agreed" boolean,
    "personal" boolean,
    "beneficiary_first_name" text default null,
    "beneficiary_last_name" text default null,
    "beneficiary_company_name" text default null
)
returns deribit.private_add_to_address_book_response_result
language sql
as $$
    
    with request as (
        select row(
            "currency",
            "type",
            "address",
            "label",
            "beneficiary_vasp_name",
            "beneficiary_vasp_did",
            "beneficiary_first_name",
            "beneficiary_last_name",
            "beneficiary_company_name",
            "beneficiary_address",
            "agreed",
            "personal"
        )::deribit.private_add_to_address_book_request as payload
    ), 
    http_response as (
        select deribit.private_jsonrpc_request(
            auth := deribit.get_auth(),
            url := '/private/add_to_address_book'::deribit.endpoint,
            request := request.payload,
            rate_limiter := 'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
        from request
    )
    select (
        jsonb_populate_record(
            null::deribit.private_add_to_address_book_response,
            convert_from((a.http_response).body, 'utf-8')::jsonb
        )
    ).result
    from http_response a

$$;

comment on function deribit.private_add_to_address_book is 'Adds new entry to address book of given type';
