/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.private_cancel_quotes_request_cancel_type as enum (
    'all',
    'currency',
    'currency_pair',
    'delta',
    'instrument',
    'instrument_kind',
    'quote_set_id'
);

create type deribit.private_cancel_quotes_request_kind as enum (
    'any',
    'combo',
    'future',
    'future_combo',
    'option',
    'option_combo',
    'spot'
);

create type deribit.private_cancel_quotes_request_currency as enum (
    'BTC',
    'ETH',
    'EURR',
    'USDC',
    'USDT'
);

create type deribit.private_cancel_quotes_request_currency_pair as enum (
    'ada_usd',
    'ada_usdc',
    'ada_usdt',
    'algo_usd',
    'algo_usdc',
    'algo_usdt',
    'avax_usd',
    'avax_usdc',
    'avax_usdt',
    'bch_usd',
    'bch_usdc',
    'bch_usdt',
    'bnb_usdt',
    'btc_usd',
    'btc_usdc',
    'btc_usde',
    'btc_usdt',
    'btc_usyc',
    'btcdvol_usdc',
    'doge_usd',
    'doge_usdc',
    'doge_usdt',
    'dot_usd',
    'dot_usdc',
    'dot_usdt',
    'eth_usd',
    'eth_usdc',
    'eth_usde',
    'eth_usdt',
    'eth_usyc',
    'ethdvol_usdc',
    'link_usd',
    'link_usdc',
    'link_usdt',
    'ltc_usd',
    'ltc_usdc',
    'ltc_usdt',
    'luna_usdt',
    'matic_usd',
    'matic_usdc',
    'matic_usdt',
    'near_usd',
    'near_usdc',
    'near_usdt',
    'paxg_btc',
    'paxg_usd',
    'paxg_usdc',
    'paxg_usdt',
    'shib_usd',
    'shib_usdc',
    'shib_usdt',
    'sol_usd',
    'sol_usdc',
    'sol_usdt',
    'steth_eth',
    'steth_usd',
    'steth_usdc',
    'steth_usdt',
    'trx_usd',
    'trx_usdc',
    'trx_usdt',
    'uni_usd',
    'uni_usdc',
    'uni_usdt',
    'usdc_usd',
    'usde_usd',
    'usde_usdc',
    'usde_usdt',
    'usyc_usdc',
    'xrp_usd',
    'xrp_usdc',
    'xrp_usdt'
);

create type deribit.private_cancel_quotes_request as (
    "detailed" boolean,
    "freeze_quotes" boolean,
    "cancel_type" deribit.private_cancel_quotes_request_cancel_type,
    "min_delta" double precision,
    "max_delta" double precision,
    "quote_set_id" text,
    "instrument_name" text,
    "kind" deribit.private_cancel_quotes_request_kind,
    "currency" deribit.private_cancel_quotes_request_currency,
    "currency_pair" deribit.private_cancel_quotes_request_currency_pair
);

comment on column deribit.private_cancel_quotes_request."detailed" is 'When detailed is set to true output format is changed. See description. Default: false';
comment on column deribit.private_cancel_quotes_request."freeze_quotes" is 'Whether or not to reject incoming quotes for 1 second after cancelling (false by default). Related to private/mass_quote request.';
comment on column deribit.private_cancel_quotes_request."cancel_type" is '(Required) Type of cancel criteria.';
comment on column deribit.private_cancel_quotes_request."min_delta" is 'Min delta to cancel by delta (for cancel_type: delta).';
comment on column deribit.private_cancel_quotes_request."max_delta" is 'Max delta to cancel by delta (for cancel_type: delta).';
comment on column deribit.private_cancel_quotes_request."quote_set_id" is 'Unique identifier for the Quote set.';
comment on column deribit.private_cancel_quotes_request."instrument_name" is 'Instrument name.';
comment on column deribit.private_cancel_quotes_request."kind" is 'Instrument kind, "combo" for any combo or "any" for all. If not provided instruments of all kinds are considered';
comment on column deribit.private_cancel_quotes_request."currency" is '(Required) The currency symbol';
comment on column deribit.private_cancel_quotes_request."currency_pair" is '(Required) The currency pair symbol';

create type deribit.private_cancel_quotes_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" double precision
);

comment on column deribit.private_cancel_quotes_response."id" is 'The id that was sent in the request';
comment on column deribit.private_cancel_quotes_response."jsonrpc" is 'The JSON-RPC version (2.0)';
comment on column deribit.private_cancel_quotes_response."result" is 'Total number of successfully cancelled quotes';

create function deribit.private_cancel_quotes(
    "cancel_type" deribit.private_cancel_quotes_request_cancel_type,
    "currency" deribit.private_cancel_quotes_request_currency,
    "currency_pair" deribit.private_cancel_quotes_request_currency_pair,
    "detailed" boolean default null,
    "freeze_quotes" boolean default null,
    "min_delta" double precision default null,
    "max_delta" double precision default null,
    "quote_set_id" text default null,
    "instrument_name" text default null,
    "kind" deribit.private_cancel_quotes_request_kind default null
)
returns double precision
language sql
as $$
    
    with request as (
        select row(
            "detailed",
            "freeze_quotes",
            "cancel_type",
            "min_delta",
            "max_delta",
            "quote_set_id",
            "instrument_name",
            "kind",
            "currency",
            "currency_pair"
        )::deribit.private_cancel_quotes_request as payload
    ), 
    http_response as (
        select deribit.private_jsonrpc_request(
            auth := deribit.get_auth(),
            url := '/private/cancel_quotes'::deribit.endpoint,
            request := request.payload,
            rate_limiter := 'deribit.matching_engine_request_log_call'::name
        ) as http_response
        from request
    )
    select (
        jsonb_populate_record(
            null::deribit.private_cancel_quotes_response,
            convert_from((a.http_response).body, 'utf-8')::jsonb
        )
    ).result
    from http_response a

$$;

comment on function deribit.private_cancel_quotes is 'Cancels quotes based on the provided type. delta cancels quotes within a Delta range defined by min_delta and max_delta. quote_set_id cancels quotes by a specific Quote Set identifier. instrument cancels all quotes associated with a particular instrument. kind cancels all quotes for a certain instrument kind. currency cancels all quotes in a specified currency. currency_pair cancels all quotes in a specified currency pair. all cancels all quotes.';
