/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.private_get_mmp_status_request_index_name as enum (
    'ada_usdc',
    'algo_usdc',
    'all',
    'avax_usdc',
    'bch_usdc',
    'bnb_usdc',
    'btc_usd',
    'btc_usdc',
    'btc_usdt',
    'btcdvol_usdc',
    'buidl_usdc',
    'doge_usdc',
    'dot_usdc',
    'eth_usd',
    'eth_usdc',
    'eth_usdt',
    'ethdvol_usdc',
    'link_usdc',
    'ltc_usdc',
    'near_usdc',
    'paxg_usdc',
    'shib_usdc',
    'sol_usdc',
    'ton_usdc',
    'trump_usdc',
    'trx_usdc',
    'uni_usdc',
    'usde_usdc',
    'xrp_usdc'
);

create type deribit.private_get_mmp_status_request as (
    "index_name" deribit.private_get_mmp_status_request_index_name,
    "mmp_group" text,
    "block_rfq" boolean
);

comment on column deribit.private_get_mmp_status_request."index_name" is 'Index identifier of derivative instrument on the platform; skipping this parameter will return all configurations';
comment on column deribit.private_get_mmp_status_request."mmp_group" is 'Specifies the MMP group for which the status is being retrieved. The index_name must be specified before using this parameter. 📖 Related Support Article: Mass Quotes Specifications';
comment on column deribit.private_get_mmp_status_request."block_rfq" is 'If true, retrieves MMP status for Block RFQ. When set, requires block_rfq scope instead of trade scope. Block RFQ MMP status is completely separate from normal order/quote MMP status.';

create type deribit.private_get_mmp_status_response_result as (
    "block_rfq" boolean,
    "frozen_until" bigint,
    "index_name" text,
    "mmp_group" text
);

comment on column deribit.private_get_mmp_status_response_result."block_rfq" is 'If true, indicates that the MMP status is for Block RFQ. Block RFQ MMP status is completely separate from normal order/quote MMP status.';
comment on column deribit.private_get_mmp_status_response_result."frozen_until" is 'Timestamp (milliseconds since the UNIX epoch) until the user will be frozen - 0 means that the user is frozen until manual reset.';
comment on column deribit.private_get_mmp_status_response_result."index_name" is 'Index identifier, matches (base) cryptocurrency with quote currency';
comment on column deribit.private_get_mmp_status_response_result."mmp_group" is 'Triggered mmp group, this parameter is optional (appears only for Mass Quote orders trigger)';

create type deribit.private_get_mmp_status_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" deribit.private_get_mmp_status_response_result[]
);

comment on column deribit.private_get_mmp_status_response."id" is 'The id that was sent in the request';
comment on column deribit.private_get_mmp_status_response."jsonrpc" is 'The JSON-RPC version (2.0)';

create function deribit.private_get_mmp_status(
    "index_name" deribit.private_get_mmp_status_request_index_name default null,
    "mmp_group" text default null,
    "block_rfq" boolean default null
)
returns setof deribit.private_get_mmp_status_response_result
language sql
as $$
    
    with request as (
        select row(
            "index_name",
            "mmp_group",
            "block_rfq"
        )::deribit.private_get_mmp_status_request as payload
    ), 
    http_response as (
        select deribit.private_jsonrpc_request(
            auth := deribit.get_auth(),
            url := '/private/get_mmp_status'::deribit.endpoint,
            request := request.payload,
            rate_limiter := 'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
        from request
    ),
    result as (
        select (jsonb_populate_record(
            null::deribit.private_get_mmp_status_response,
            convert_from((http_response.http_response).body, 'utf-8')::jsonb)
        ).result
        from http_response
    )
    select
        (b)."block_rfq"::boolean,
        (b)."frozen_until"::bigint,
        (b)."index_name"::text,
        (b)."mmp_group"::text
    from (
        select (unnest(r.data)) b
        from result r(data)
    ) a
    
$$;

comment on function deribit.private_get_mmp_status is 'Get MMP status for triggered index (or group). If the parameter is not provided, a list of all triggered MMP statuses is returned.';
