/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.private_change_margin_model_request_margin_model as enum (
    'cross_pm',
    'cross_sm',
    'segregated_pm',
    'segregated_sm'
);

create type deribit.private_change_margin_model_request as (
    "user_id" bigint,
    "margin_model" deribit.private_change_margin_model_request_margin_model,
    "dry_run" boolean
);

comment on column deribit.private_change_margin_model_request."user_id" is 'Id of a (sub)account - by default current user id is used';
comment on column deribit.private_change_margin_model_request."margin_model" is '(Required) Margin model';
comment on column deribit.private_change_margin_model_request."dry_run" is 'If true request returns the result without switching the margining model. Default: false';

create type deribit.private_change_margin_model_response_old_state as (
    "available_balance" double precision,
    "initial_margin_rate" double precision,
    "maintenance_margin_rate" double precision
);

comment on column deribit.private_change_margin_model_response_old_state."available_balance" is 'Available balance before change';
comment on column deribit.private_change_margin_model_response_old_state."initial_margin_rate" is 'Initial margin rate before change';
comment on column deribit.private_change_margin_model_response_old_state."maintenance_margin_rate" is 'Maintenance margin rate before change';

create type deribit.private_change_margin_model_response_new_state as (
    "available_balance" double precision,
    "initial_margin_rate" double precision,
    "maintenance_margin_rate" double precision
);

comment on column deribit.private_change_margin_model_response_new_state."available_balance" is 'Available balance after change';
comment on column deribit.private_change_margin_model_response_new_state."initial_margin_rate" is 'Initial margin rate after change';
comment on column deribit.private_change_margin_model_response_new_state."maintenance_margin_rate" is 'Maintenance margin rate after change';

create type deribit.private_change_margin_model_response_result as (
    "currency" text,
    "new_state" deribit.private_change_margin_model_response_new_state,
    "old_state" deribit.private_change_margin_model_response_old_state
);

comment on column deribit.private_change_margin_model_response_result."currency" is 'Currency, i.e "BTC", "ETH", "USDC"';
comment on column deribit.private_change_margin_model_response_result."new_state" is 'Represents portfolio state after change';
comment on column deribit.private_change_margin_model_response_result."old_state" is 'Represents portfolio state before change';

create type deribit.private_change_margin_model_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" deribit.private_change_margin_model_response_result[]
);

comment on column deribit.private_change_margin_model_response."id" is 'The id that was sent in the request';
comment on column deribit.private_change_margin_model_response."jsonrpc" is 'The JSON-RPC version (2.0)';

create function deribit.private_change_margin_model(
    "margin_model" deribit.private_change_margin_model_request_margin_model,
    "user_id" bigint default null,
    "dry_run" boolean default null
)
returns setof deribit.private_change_margin_model_response_result
language sql
as $$
    
    with request as (
        select row(
            "user_id",
            "margin_model",
            "dry_run"
        )::deribit.private_change_margin_model_request as payload
    ), 
    http_response as (
        select deribit.private_jsonrpc_request(
            auth := deribit.get_auth(),
            url := '/private/change_margin_model'::deribit.endpoint,
            request := request.payload,
            rate_limiter := 'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
        from request
    ),
    result as (
        select (jsonb_populate_record(
            null::deribit.private_change_margin_model_response,
            convert_from((http_response.http_response).body, 'utf-8')::jsonb)
        ).result
        from http_response
    )
    select
        (b)."currency"::text,
        (b)."new_state"::deribit.private_change_margin_model_response_new_state,
        (b)."old_state"::deribit.private_change_margin_model_response_old_state
    from (
        select (unnest(r.data)) b
        from result r(data)
    ) a
    
$$;

comment on function deribit.private_change_margin_model is 'Change margin model';
