/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.private_get_order_margin_by_ids_request as (
    "ids" text[]
);

comment on column deribit.private_get_order_margin_by_ids_request."ids" is '(Required) Ids of orders';

create type deribit.private_get_order_margin_by_ids_response_result as (
    "initial_margin" double precision,
    "initial_margin_currency" text,
    "order_id" text
);

comment on column deribit.private_get_order_margin_by_ids_response_result."initial_margin" is 'Initial margin of order';
comment on column deribit.private_get_order_margin_by_ids_response_result."initial_margin_currency" is 'Currency of initial margin';
comment on column deribit.private_get_order_margin_by_ids_response_result."order_id" is 'Unique order identifier';

create type deribit.private_get_order_margin_by_ids_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" deribit.private_get_order_margin_by_ids_response_result[]
);

comment on column deribit.private_get_order_margin_by_ids_response."id" is 'The id that was sent in the request';
comment on column deribit.private_get_order_margin_by_ids_response."jsonrpc" is 'The JSON-RPC version (2.0)';

create function deribit.private_get_order_margin_by_ids(
    "ids" text[]
)
returns setof deribit.private_get_order_margin_by_ids_response_result
language sql
as $$
    
    with request as (
        select row(
            "ids"
        )::deribit.private_get_order_margin_by_ids_request as payload
    ), 
    http_response as (
        select deribit.private_jsonrpc_request(
            auth := deribit.get_auth(),
            url := '/private/get_order_margin_by_ids'::deribit.endpoint,
            request := request.payload,
            rate_limiter := 'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
        from request
    ),
    result as (
        select (jsonb_populate_record(
            null::deribit.private_get_order_margin_by_ids_response,
            convert_from((http_response.http_response).body, 'utf-8')::jsonb)
        ).result
        from http_response
    )
    select
        (b)."initial_margin"::double precision,
        (b)."initial_margin_currency"::text,
        (b)."order_id"::text
    from (
        select (unnest(r.data)) b
        from result r(data)
    ) a
    
$$;

comment on function deribit.private_get_order_margin_by_ids is 'Retrieves initial margins of given orders';
