/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.private_set_mmp_config_request_index_name as enum (
    'ada_usdc',
    'ada_usdt',
    'algo_usdc',
    'algo_usdt',
    'avax_usdc',
    'avax_usdt',
    'bch_usdc',
    'bch_usdt',
    'bnb_usdt',
    'btc_usd',
    'btc_usdc',
    'btc_usdt',
    'btcdvol_usdc',
    'doge_usdc',
    'doge_usdt',
    'dot_usdc',
    'dot_usdt',
    'eth_usd',
    'eth_usdc',
    'eth_usdt',
    'ethdvol_usdc',
    'link_usdc',
    'link_usdt',
    'ltc_usdc',
    'ltc_usdt',
    'luna_usdt',
    'matic_usdc',
    'matic_usdt',
    'near_usdc',
    'near_usdt',
    'shib_usdc',
    'shib_usdt',
    'sol_usdc',
    'sol_usdt',
    'trx_usdc',
    'trx_usdt',
    'uni_usdc',
    'uni_usdt',
    'xrp_usdc',
    'xrp_usdt'
);

create type deribit.private_set_mmp_config_request as (
    "index_name" deribit.private_set_mmp_config_request_index_name,
    "interval" bigint,
    "frozen_time" bigint,
    "mmp_group" text,
    "quantity_limit" double precision,
    "delta_limit" double precision
);

comment on column deribit.private_set_mmp_config_request."index_name" is '(Required) Index identifier of derivative instrument on the platform';
comment on column deribit.private_set_mmp_config_request."interval" is '(Required) MMP Interval in seconds, if set to 0 MMP is removed';
comment on column deribit.private_set_mmp_config_request."frozen_time" is '(Required) MMP frozen time in seconds, if set to 0 manual reset is required';
comment on column deribit.private_set_mmp_config_request."mmp_group" is 'Designates the MMP group for which the configuration is being set. If the specified group is already associated with a different index_name, an error is returned. This parameter enables distinct configurations for each MMP group, linked to particular index_name';
comment on column deribit.private_set_mmp_config_request."quantity_limit" is 'Quantity limit, positive value';
comment on column deribit.private_set_mmp_config_request."delta_limit" is 'Delta limit, positive value';

create type deribit.private_set_mmp_config_response_result as (
    "delta_limit" double precision,
    "frozen_time" bigint,
    "index_name" text,
    "interval" bigint,
    "mmp_group" text,
    "quantity_limit" double precision
);

comment on column deribit.private_set_mmp_config_response_result."delta_limit" is 'Delta limit';
comment on column deribit.private_set_mmp_config_response_result."frozen_time" is 'MMP frozen time in seconds, if set to 0 manual reset is required';
comment on column deribit.private_set_mmp_config_response_result."index_name" is 'Index identifier, matches (base) cryptocurrency with quote currency';
comment on column deribit.private_set_mmp_config_response_result."interval" is 'MMP Interval in seconds, if set to 0 MMP is disabled';
comment on column deribit.private_set_mmp_config_response_result."mmp_group" is 'Specified MMP Group';
comment on column deribit.private_set_mmp_config_response_result."quantity_limit" is 'Quantity limit';

create type deribit.private_set_mmp_config_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" deribit.private_set_mmp_config_response_result[]
);

comment on column deribit.private_set_mmp_config_response."id" is 'The id that was sent in the request';
comment on column deribit.private_set_mmp_config_response."jsonrpc" is 'The JSON-RPC version (2.0)';

create function deribit.private_set_mmp_config(
    auth deribit.auth
,    "index_name" deribit.private_set_mmp_config_request_index_name,
    "interval" bigint,
    "frozen_time" bigint,
    "mmp_group" text default null,
    "quantity_limit" double precision default null,
    "delta_limit" double precision default null
)
returns setof deribit.private_set_mmp_config_response_result
language sql
as $$
    
    with request as (
        select row(
            "index_name",
            "interval",
            "frozen_time",
            "mmp_group",
            "quantity_limit",
            "delta_limit"
        )::deribit.private_set_mmp_config_request as payload
    ), 
    http_response as (
        select deribit.private_jsonrpc_request(
            auth := auth,             
            url := '/private/set_mmp_config'::deribit.endpoint, 
            request := request.payload, 
            rate_limiter := 'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
        from request
    )
        , result as (
select (jsonb_populate_record(
                        null::deribit.private_set_mmp_config_response,
                        convert_from((http_response.http_response).body, 'utf-8')::jsonb)
             ).result
        from http_response
    )
    select
        (b)."delta_limit"::double precision,
        (b)."frozen_time"::bigint,
        (b)."index_name"::text,
        (b)."interval"::bigint,
        (b)."mmp_group"::text,
        (b)."quantity_limit"::double precision
    from (
        select (unnest(r.data)) b
        from result r(data)
    ) a
    
$$;

comment on function deribit.private_set_mmp_config is 'Set config for MMP - triggers MMP reset';
