/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.private_cancel_all_by_currency_pair_request_currency_pair as enum (
    'ada_usd',
    'ada_usdc',
    'ada_usdt',
    'algo_usd',
    'algo_usdc',
    'algo_usdt',
    'avax_usd',
    'avax_usdc',
    'avax_usdt',
    'bch_usd',
    'bch_usdc',
    'bch_usdt',
    'bnb_usdt',
    'btc_usd',
    'btc_usdc',
    'btc_usdt',
    'btcdvol_usdc',
    'doge_usd',
    'doge_usdc',
    'doge_usdt',
    'dot_usd',
    'dot_usdc',
    'dot_usdt',
    'eth_usd',
    'eth_usdc',
    'eth_usdt',
    'ethdvol_usdc',
    'link_usd',
    'link_usdc',
    'link_usdt',
    'ltc_usd',
    'ltc_usdc',
    'ltc_usdt',
    'luna_usdt',
    'matic_usd',
    'matic_usdc',
    'matic_usdt',
    'near_usd',
    'near_usdc',
    'near_usdt',
    'shib_usd',
    'shib_usdc',
    'shib_usdt',
    'sol_usd',
    'sol_usdc',
    'sol_usdt',
    'trx_usd',
    'trx_usdc',
    'trx_usdt',
    'uni_usd',
    'uni_usdc',
    'uni_usdt',
    'usdc_usd',
    'xrp_usd',
    'xrp_usdc',
    'xrp_usdt'
);

create type deribit.private_cancel_all_by_currency_pair_request_kind as enum (
    'any',
    'combo',
    'future',
    'future_combo',
    'option',
    'option_combo',
    'spot'
);

create type deribit.private_cancel_all_by_currency_pair_request_type as enum (
    'all',
    'limit',
    'stop',
    'take',
    'trailing_stop',
    'trigger_all'
);

create type deribit.private_cancel_all_by_currency_pair_request as (
    "currency_pair" deribit.private_cancel_all_by_currency_pair_request_currency_pair,
    "kind" deribit.private_cancel_all_by_currency_pair_request_kind,
    "type" deribit.private_cancel_all_by_currency_pair_request_type,
    "detailed" boolean,
    "freeze_quotes" boolean
);

comment on column deribit.private_cancel_all_by_currency_pair_request."currency_pair" is '(Required) The currency pair symbol';
comment on column deribit.private_cancel_all_by_currency_pair_request."kind" is 'Instrument kind, "combo" for any combo or "any" for all. If not provided instruments of all kinds are considered';
comment on column deribit.private_cancel_all_by_currency_pair_request."type" is 'Order type - limit, stop, take, trigger_all or all, default - all';
comment on column deribit.private_cancel_all_by_currency_pair_request."detailed" is 'When detailed is set to true output format is changed. See description. Default: false';
comment on column deribit.private_cancel_all_by_currency_pair_request."freeze_quotes" is 'Whether or not to reject incoming quotes for 1 second after cancelling (false by default). Related to private/mass_quote request.';

create type deribit.private_cancel_all_by_currency_pair_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" double precision
);

comment on column deribit.private_cancel_all_by_currency_pair_response."id" is 'The id that was sent in the request';
comment on column deribit.private_cancel_all_by_currency_pair_response."jsonrpc" is 'The JSON-RPC version (2.0)';
comment on column deribit.private_cancel_all_by_currency_pair_response."result" is 'Total number of successfully cancelled orders';

create function deribit.private_cancel_all_by_currency_pair(
    "currency_pair" deribit.private_cancel_all_by_currency_pair_request_currency_pair,
    "kind" deribit.private_cancel_all_by_currency_pair_request_kind default null,
    "type" deribit.private_cancel_all_by_currency_pair_request_type default null,
    "detailed" boolean default null,
    "freeze_quotes" boolean default null
)
returns double precision
language sql
as $$
    
    with request as (
        select row(
            "currency_pair",
            "kind",
            "type",
            "detailed",
            "freeze_quotes"
        )::deribit.private_cancel_all_by_currency_pair_request as payload
    ), 
    http_response as (
        select deribit.private_jsonrpc_request(
            auth := deribit.get_auth(),
            url := '/private/cancel_all_by_currency_pair'::deribit.endpoint,
            request := request.payload,
            rate_limiter := 'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
        from request
    )
    select (
        jsonb_populate_record(
            null::deribit.private_cancel_all_by_currency_pair_response,
            convert_from((a.http_response).body, 'utf-8')::jsonb
        )
    ).result
    from http_response a

$$;

comment on function deribit.private_cancel_all_by_currency_pair is 'Cancels all orders by currency pair, optionally filtered by instrument kind and/or order type.';
