/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.private_cancel_all_by_currency_request_currency as enum (
    'BTC',
    'ETH',
    'EURR',
    'USDC',
    'USDT'
);

create type deribit.private_cancel_all_by_currency_request_kind as enum (
    'any',
    'combo',
    'future',
    'future_combo',
    'option',
    'option_combo',
    'spot'
);

create type deribit.private_cancel_all_by_currency_request_type as enum (
    'all',
    'limit',
    'stop',
    'take',
    'trailing_stop',
    'trigger_all'
);

create type deribit.private_cancel_all_by_currency_request as (
    "currency" deribit.private_cancel_all_by_currency_request_currency,
    "kind" deribit.private_cancel_all_by_currency_request_kind,
    "type" deribit.private_cancel_all_by_currency_request_type,
    "detailed" boolean,
    "freeze_quotes" boolean
);

comment on column deribit.private_cancel_all_by_currency_request."currency" is '(Required) The currency symbol';
comment on column deribit.private_cancel_all_by_currency_request."kind" is 'Instrument kind, "combo" for any combo or "any" for all. If not provided instruments of all kinds are considered';
comment on column deribit.private_cancel_all_by_currency_request."type" is 'Order type - limit, stop, take, trigger_all or all, default - all';
comment on column deribit.private_cancel_all_by_currency_request."detailed" is 'When detailed is set to true output format is changed. See description. Default: false';
comment on column deribit.private_cancel_all_by_currency_request."freeze_quotes" is 'Whether or not to reject incoming quotes for 1 second after cancelling (false by default). Related to private/mass_quote request.';

create type deribit.private_cancel_all_by_currency_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" double precision
);

comment on column deribit.private_cancel_all_by_currency_response."id" is 'The id that was sent in the request';
comment on column deribit.private_cancel_all_by_currency_response."jsonrpc" is 'The JSON-RPC version (2.0)';
comment on column deribit.private_cancel_all_by_currency_response."result" is 'Total number of successfully cancelled orders';

create function deribit.private_cancel_all_by_currency(
    "currency" deribit.private_cancel_all_by_currency_request_currency,
    "kind" deribit.private_cancel_all_by_currency_request_kind default null,
    "type" deribit.private_cancel_all_by_currency_request_type default null,
    "detailed" boolean default null,
    "freeze_quotes" boolean default null
)
returns double precision
language sql
as $$
    
    with request as (
        select row(
            "currency",
            "kind",
            "type",
            "detailed",
            "freeze_quotes"
        )::deribit.private_cancel_all_by_currency_request as payload
    ), 
    http_response as (
        select deribit.private_jsonrpc_request(
            auth := deribit.get_auth(),
            url := '/private/cancel_all_by_currency'::deribit.endpoint,
            request := request.payload,
            rate_limiter := 'deribit.matching_engine_request_log_call'::name
        ) as http_response
        from request
    )
    select (
        jsonb_populate_record(
            null::deribit.private_cancel_all_by_currency_response,
            convert_from((a.http_response).body, 'utf-8')::jsonb
        )
    ).result
    from http_response a

$$;

comment on function deribit.private_cancel_all_by_currency is 'Cancels all orders by currency, optionally filtered by instrument kind and/or order type.';
