/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.private_get_subaccounts_details_request_currency as enum (
    'BTC',
    'ETH',
    'EURR',
    'USDC',
    'USDT'
);

create type deribit.private_get_subaccounts_details_request as (
    "currency" deribit.private_get_subaccounts_details_request_currency,
    "with_open_orders" boolean
);

comment on column deribit.private_get_subaccounts_details_request."currency" is '(Required) The currency symbol';
comment on column deribit.private_get_subaccounts_details_request."with_open_orders" is 'Optional parameter to ask for open orders list, default: false';

create type deribit.private_get_subaccounts_details_response_position as (
    "average_price" double precision,
    "average_price_usd" double precision,
    "delta" double precision,
    "direction" text,
    "floating_profit_loss" double precision,
    "floating_profit_loss_usd" double precision,
    "gamma" double precision,
    "index_price" double precision,
    "initial_margin" double precision,
    "instrument_name" text,
    "interest_value" double precision,
    "kind" text,
    "leverage" bigint,
    "maintenance_margin" double precision,
    "mark_price" double precision,
    "realized_funding" double precision,
    "realized_profit_loss" double precision,
    "settlement_price" double precision,
    "size" double precision,
    "size_currency" double precision,
    "theta" double precision,
    "total_profit_loss" double precision,
    "vega" double precision
);

comment on column deribit.private_get_subaccounts_details_response_position."average_price" is 'Average price of trades that built this position';
comment on column deribit.private_get_subaccounts_details_response_position."average_price_usd" is 'Only for options, average price in USD';
comment on column deribit.private_get_subaccounts_details_response_position."delta" is 'Delta parameter';
comment on column deribit.private_get_subaccounts_details_response_position."direction" is 'Direction: buy, sell or zero';
comment on column deribit.private_get_subaccounts_details_response_position."floating_profit_loss" is 'Floating profit or loss';
comment on column deribit.private_get_subaccounts_details_response_position."floating_profit_loss_usd" is 'Only for options, floating profit or loss in USD';
comment on column deribit.private_get_subaccounts_details_response_position."gamma" is 'Only for options, Gamma parameter';
comment on column deribit.private_get_subaccounts_details_response_position."index_price" is 'Current index price';
comment on column deribit.private_get_subaccounts_details_response_position."initial_margin" is 'Initial margin';
comment on column deribit.private_get_subaccounts_details_response_position."instrument_name" is 'Unique instrument identifier';
comment on column deribit.private_get_subaccounts_details_response_position."interest_value" is 'Value used to calculate realized_funding (perpetual only)';
comment on column deribit.private_get_subaccounts_details_response_position."kind" is 'Instrument kind: "future", "option", "spot", "future_combo", "option_combo"';
comment on column deribit.private_get_subaccounts_details_response_position."leverage" is 'Current available leverage for future position';
comment on column deribit.private_get_subaccounts_details_response_position."maintenance_margin" is 'Maintenance margin';
comment on column deribit.private_get_subaccounts_details_response_position."mark_price" is 'Current mark price for position''s instrument';
comment on column deribit.private_get_subaccounts_details_response_position."realized_funding" is 'Realized Funding in current session included in session realized profit or loss, only for positions of perpetual instruments';
comment on column deribit.private_get_subaccounts_details_response_position."realized_profit_loss" is 'Realized profit or loss';
comment on column deribit.private_get_subaccounts_details_response_position."settlement_price" is 'Optional (not added for spot). Last settlement price for position''s instrument 0 if instrument wasn''t settled yet';
comment on column deribit.private_get_subaccounts_details_response_position."size" is 'Position size for futures size in quote currency (e.g. USD), for options size is in base currency (e.g. BTC)';
comment on column deribit.private_get_subaccounts_details_response_position."size_currency" is 'Only for futures, position size in base currency';
comment on column deribit.private_get_subaccounts_details_response_position."theta" is 'Only for options, Theta parameter';
comment on column deribit.private_get_subaccounts_details_response_position."total_profit_loss" is 'Profit or loss from position';
comment on column deribit.private_get_subaccounts_details_response_position."vega" is 'Only for options, Vega parameter';

create type deribit.private_get_subaccounts_details_response_open_order as (
    "quote" boolean,
    "triggered" boolean,
    "mobile" boolean,
    "app_name" text,
    "implv" double precision,
    "refresh_amount" double precision,
    "usd" double precision,
    "oto_order_ids" text[],
    "api" boolean,
    "average_price" double precision,
    "advanced" text,
    "order_id" text,
    "post_only" boolean,
    "filled_amount" double precision,
    "trigger" text,
    "trigger_order_id" text,
    "direction" text,
    "contracts" double precision,
    "is_secondary_oto" boolean,
    "replaced" boolean,
    "mmp_group" text,
    "mmp" boolean,
    "last_update_timestamp" bigint,
    "creation_timestamp" bigint,
    "cancel_reason" text,
    "mmp_cancelled" boolean,
    "quote_id" text,
    "order_state" text,
    "is_rebalance" boolean,
    "reject_post_only" boolean,
    "label" text,
    "is_liquidation" boolean,
    "price" text,
    "web" boolean,
    "time_in_force" text,
    "trigger_reference_price" double precision,
    "display_amount" double precision,
    "order_type" text,
    "is_primary_otoco" boolean,
    "original_order_type" text,
    "block_trade" boolean,
    "trigger_price" double precision,
    "oco_ref" text,
    "trigger_offset" double precision,
    "quote_set_id" text,
    "auto_replaced" boolean,
    "reduce_only" boolean,
    "amount" double precision,
    "risk_reducing" boolean,
    "instrument_name" text,
    "trigger_fill_condition" text,
    "primary_order_id" text
);

comment on column deribit.private_get_subaccounts_details_response_open_order."quote" is 'If order is a quote. Present only if true.';
comment on column deribit.private_get_subaccounts_details_response_open_order."triggered" is 'Whether the trigger order has been triggered';
comment on column deribit.private_get_subaccounts_details_response_open_order."mobile" is 'optional field with value true added only when created with Mobile Application';
comment on column deribit.private_get_subaccounts_details_response_open_order."app_name" is 'The name of the application that placed the order on behalf of the user (optional).';
comment on column deribit.private_get_subaccounts_details_response_open_order."implv" is 'Implied volatility in percent. (Only if advanced="implv")';
comment on column deribit.private_get_subaccounts_details_response_open_order."refresh_amount" is 'The initial display amount of iceberg order. Iceberg order display amount will be refreshed to that value after match consuming actual display amount. Absent for other types of orders';
comment on column deribit.private_get_subaccounts_details_response_open_order."usd" is 'Option price in USD (Only if advanced="usd")';
comment on column deribit.private_get_subaccounts_details_response_open_order."oto_order_ids" is 'The Ids of the orders that will be triggered if the order is filled';
comment on column deribit.private_get_subaccounts_details_response_open_order."api" is 'true if created with API';
comment on column deribit.private_get_subaccounts_details_response_open_order."average_price" is 'Average fill price of the order';
comment on column deribit.private_get_subaccounts_details_response_open_order."advanced" is 'advanced type: "usd" or "implv" (Only for options; field is omitted if not applicable).';
comment on column deribit.private_get_subaccounts_details_response_open_order."order_id" is 'Unique order identifier';
comment on column deribit.private_get_subaccounts_details_response_open_order."post_only" is 'true for post-only orders only';
comment on column deribit.private_get_subaccounts_details_response_open_order."filled_amount" is 'Filled amount of the order. For perpetual and futures the filled_amount is in USD units, for options - in units or corresponding cryptocurrency contracts, e.g., BTC or ETH.';
comment on column deribit.private_get_subaccounts_details_response_open_order."trigger" is 'Trigger type (only for trigger orders). Allowed values: "index_price", "mark_price", "last_price".';
comment on column deribit.private_get_subaccounts_details_response_open_order."trigger_order_id" is 'Id of the trigger order that created the order (Only for orders that were created by triggered orders).';
comment on column deribit.private_get_subaccounts_details_response_open_order."direction" is 'Direction: buy, or sell';
comment on column deribit.private_get_subaccounts_details_response_open_order."contracts" is 'It represents the order size in contract units. (Optional, may be absent in historical data).';
comment on column deribit.private_get_subaccounts_details_response_open_order."is_secondary_oto" is 'true if the order is an order that can be triggered by another order, otherwise not present.';
comment on column deribit.private_get_subaccounts_details_response_open_order."replaced" is 'true if the order was edited (by user or - in case of advanced options orders - by pricing engine), otherwise false.';
comment on column deribit.private_get_subaccounts_details_response_open_order."mmp_group" is 'Name of the MMP group supplied in the private/mass_quote request. Only present for quote orders.';
comment on column deribit.private_get_subaccounts_details_response_open_order."mmp" is 'true if the order is a MMP order, otherwise false.';
comment on column deribit.private_get_subaccounts_details_response_open_order."last_update_timestamp" is 'The timestamp (milliseconds since the Unix epoch)';
comment on column deribit.private_get_subaccounts_details_response_open_order."creation_timestamp" is 'The timestamp (milliseconds since the Unix epoch)';
comment on column deribit.private_get_subaccounts_details_response_open_order."cancel_reason" is 'Enumerated reason behind cancel "user_request", "autoliquidation", "cancel_on_disconnect", "risk_mitigation", "pme_risk_reduction" (portfolio margining risk reduction), "pme_account_locked" (portfolio margining account locked per currency), "position_locked", "mmp_trigger" (market maker protection), "mmp_config_curtailment" (market maker configured quantity decreased), "edit_post_only_reject" (cancelled on edit because of reject_post_only setting), "oco_other_closed" (the oco order linked to this order was closed), "oto_primary_closed" (the oto primary order that was going to trigger this order was cancelled), "settlement" (closed because of a settlement)';
comment on column deribit.private_get_subaccounts_details_response_open_order."mmp_cancelled" is 'true if order was cancelled by mmp trigger (optional)';
comment on column deribit.private_get_subaccounts_details_response_open_order."quote_id" is 'The same QuoteID as supplied in the private/mass_quote request. Only present for quote orders.';
comment on column deribit.private_get_subaccounts_details_response_open_order."order_state" is 'Order state: "open", "filled", "rejected", "cancelled", "untriggered"';
comment on column deribit.private_get_subaccounts_details_response_open_order."is_rebalance" is 'Optional (only for spot). true if order was automatically created during cross-collateral balance restoration';
comment on column deribit.private_get_subaccounts_details_response_open_order."reject_post_only" is 'true if order has reject_post_only flag (field is present only when post_only is true)';
comment on column deribit.private_get_subaccounts_details_response_open_order."label" is 'User defined label (up to 64 characters)';
comment on column deribit.private_get_subaccounts_details_response_open_order."is_liquidation" is 'Optional (not added for spot). true if order was automatically created during liquidation';
comment on column deribit.private_get_subaccounts_details_response_open_order."price" is 'Price in base currency or "market_price" in case of open trigger market orders';
comment on column deribit.private_get_subaccounts_details_response_open_order."web" is 'true if created via Deribit frontend (optional)';
comment on column deribit.private_get_subaccounts_details_response_open_order."time_in_force" is 'Order time in force: "good_til_cancelled", "good_til_day", "fill_or_kill" or "immediate_or_cancel"';
comment on column deribit.private_get_subaccounts_details_response_open_order."trigger_reference_price" is 'The price of the given trigger at the time when the order was placed (Only for trailing trigger orders)';
comment on column deribit.private_get_subaccounts_details_response_open_order."display_amount" is 'The actual display amount of iceberg order. Absent for other types of orders.';
comment on column deribit.private_get_subaccounts_details_response_open_order."order_type" is 'Order type: "limit", "market", "stop_limit", "stop_market"';
comment on column deribit.private_get_subaccounts_details_response_open_order."is_primary_otoco" is 'true if the order is an order that can trigger an OCO pair, otherwise not present.';
comment on column deribit.private_get_subaccounts_details_response_open_order."original_order_type" is 'Original order type. Optional field';
comment on column deribit.private_get_subaccounts_details_response_open_order."block_trade" is 'true if order made from block_trade trade, added only in that case.';
comment on column deribit.private_get_subaccounts_details_response_open_order."trigger_price" is 'Trigger price (Only for future trigger orders)';
comment on column deribit.private_get_subaccounts_details_response_open_order."oco_ref" is 'Unique reference that identifies a one_cancels_others (OCO) pair.';
comment on column deribit.private_get_subaccounts_details_response_open_order."trigger_offset" is 'The maximum deviation from the price peak beyond which the order will be triggered (Only for trailing trigger orders)';
comment on column deribit.private_get_subaccounts_details_response_open_order."quote_set_id" is 'Identifier of the QuoteSet supplied in the private/mass_quote request. Only present for quote orders.';
comment on column deribit.private_get_subaccounts_details_response_open_order."auto_replaced" is 'Options, advanced orders only - true if last modification of the order was performed by the pricing engine, otherwise false.';
comment on column deribit.private_get_subaccounts_details_response_open_order."reduce_only" is 'Optional (not added for spot). ''true for reduce-only orders only''';
comment on column deribit.private_get_subaccounts_details_response_open_order."amount" is 'It represents the requested order size. For perpetual and inverse futures the amount is in USD units. For options and linear futures and it is the underlying base currency coin.';
comment on column deribit.private_get_subaccounts_details_response_open_order."risk_reducing" is 'true if the order is marked by the platform as a risk reducing order (can apply only to orders placed by PM users), otherwise false.';
comment on column deribit.private_get_subaccounts_details_response_open_order."instrument_name" is 'Unique instrument identifier';
comment on column deribit.private_get_subaccounts_details_response_open_order."trigger_fill_condition" is 'The fill condition of the linked order (Only for linked order types), default: first_hit. "first_hit" - any execution of the primary order will fully cancel/place all secondary orders. "complete_fill" - a complete execution (meaning the primary order no longer exists) will cancel/place the secondary orders. "incremental" - any fill of the primary order will cause proportional partial cancellation/placement of the secondary order. The amount that will be subtracted/added to the secondary order will be rounded down to the contract size.';
comment on column deribit.private_get_subaccounts_details_response_open_order."primary_order_id" is 'Unique order identifier';

create type deribit.private_get_subaccounts_details_response_result as (
    "open_orders" deribit.private_get_subaccounts_details_response_open_order[],
    "positions" deribit.private_get_subaccounts_details_response_position[],
    "uid" bigint
);

comment on column deribit.private_get_subaccounts_details_response_result."uid" is 'Account/Subaccount identifier';

create type deribit.private_get_subaccounts_details_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" deribit.private_get_subaccounts_details_response_result[]
);

comment on column deribit.private_get_subaccounts_details_response."id" is 'The id that was sent in the request';
comment on column deribit.private_get_subaccounts_details_response."jsonrpc" is 'The JSON-RPC version (2.0)';

create function deribit.private_get_subaccounts_details(
    "currency" deribit.private_get_subaccounts_details_request_currency,
    "with_open_orders" boolean default null
)
returns setof deribit.private_get_subaccounts_details_response_result
language sql
as $$
    
    with request as (
        select row(
            "currency",
            "with_open_orders"
        )::deribit.private_get_subaccounts_details_request as payload
    ), 
    http_response as (
        select deribit.private_jsonrpc_request(
            auth := deribit.get_auth(),
            url := '/private/get_subaccounts_details'::deribit.endpoint,
            request := request.payload,
            rate_limiter := 'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
        from request
    ),
    result as (
        select (jsonb_populate_record(
            null::deribit.private_get_subaccounts_details_response,
            convert_from((http_response.http_response).body, 'utf-8')::jsonb)
        ).result
        from http_response
    )
    select
        (b)."open_orders"::deribit.private_get_subaccounts_details_response_open_order[],
        (b)."positions"::deribit.private_get_subaccounts_details_response_position[],
        (b)."uid"::bigint
    from (
        select (unnest(r.data)) b
        from result r(data)
    ) a
    
$$;

comment on function deribit.private_get_subaccounts_details is 'Get subaccounts positions';
