/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.private_get_affiliate_program_info_response_received as (
    "btc" double precision,
    "eth" double precision
);

comment on column deribit.private_get_affiliate_program_info_response_received."btc" is 'Total payout received in BTC';
comment on column deribit.private_get_affiliate_program_info_response_received."eth" is 'Total payout received in ETH';

create type deribit.private_get_affiliate_program_info_response_result as (
    "is_enabled" boolean,
    "link" text,
    "number_of_affiliates" double precision,
    "received" deribit.private_get_affiliate_program_info_response_received
);

comment on column deribit.private_get_affiliate_program_info_response_result."is_enabled" is 'Status of affiliate program';
comment on column deribit.private_get_affiliate_program_info_response_result."link" is 'Affiliate link';
comment on column deribit.private_get_affiliate_program_info_response_result."number_of_affiliates" is 'Number of affiliates';

create type deribit.private_get_affiliate_program_info_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" deribit.private_get_affiliate_program_info_response_result
);

comment on column deribit.private_get_affiliate_program_info_response."id" is 'The id that was sent in the request';
comment on column deribit.private_get_affiliate_program_info_response."jsonrpc" is 'The JSON-RPC version (2.0)';

create function deribit.private_get_affiliate_program_info(
    auth deribit.auth
)
returns deribit.private_get_affiliate_program_info_response_result
language sql
as $$
    with http_response as (
        select deribit.private_jsonrpc_request(auth, '/private/get_affiliate_program_info'::deribit.endpoint, 
            null::text, 
            'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
    )
select (jsonb_populate_record(
        null::deribit.private_get_affiliate_program_info_response, 
        convert_from((a.http_response).body, 'utf-8')::jsonb)).result
    from http_response a

$$;

comment on function deribit.private_get_affiliate_program_info is 'Retrieves user`s affiliates count, payouts and link.';
