/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.private_get_user_locks_response_result as (
    "currency" text,
    "enabled" boolean,
    "message" text
);

comment on column deribit.private_get_user_locks_response_result."currency" is 'Currency, i.e "BTC", "ETH", "USDC"';
comment on column deribit.private_get_user_locks_response_result."enabled" is 'Value is set to ''true'' when user account is locked in currency';
comment on column deribit.private_get_user_locks_response_result."message" is 'Optional information for user why his account is locked';

create type deribit.private_get_user_locks_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" deribit.private_get_user_locks_response_result[]
);

comment on column deribit.private_get_user_locks_response."id" is 'The id that was sent in the request';
comment on column deribit.private_get_user_locks_response."jsonrpc" is 'The JSON-RPC version (2.0)';

create function deribit.private_get_user_locks()
returns setof deribit.private_get_user_locks_response_result
language sql
as $$
    with http_response as (
        select deribit.private_jsonrpc_request(
            auth := deribit.get_auth(),
            url := '/private/get_user_locks'::deribit.endpoint,
            request := null::text,
            rate_limiter := 'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
    ),
    result as (
        select (jsonb_populate_record(
            null::deribit.private_get_user_locks_response,
            convert_from((http_response.http_response).body, 'utf-8')::jsonb)
        ).result
        from http_response
    )
    select
        (b)."currency"::text,
        (b)."enabled"::boolean,
        (b)."message"::text
    from (
        select (unnest(r.data)) b
        from result r(data)
    ) a
    
$$;

comment on function deribit.private_get_user_locks is 'Retrieves information about locks on user account';
