/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.private_get_account_summary_request_currency as enum (
    'BNB',
    'BTC',
    'ETH',
    'ETHW',
    'EURR',
    'MATIC',
    'PAXG',
    'SOL',
    'STETH',
    'USDC',
    'USDE',
    'USDT',
    'USYC',
    'XRP'
);

create type deribit.private_get_account_summary_request as (
    "currency" deribit.private_get_account_summary_request_currency,
    "subaccount_id" bigint,
    "extended" boolean
);

comment on column deribit.private_get_account_summary_request."currency" is '(Required) The currency symbol';
comment on column deribit.private_get_account_summary_request."subaccount_id" is 'The user id for the subaccount';
comment on column deribit.private_get_account_summary_request."extended" is 'Include additional fields';

create type deribit.private_get_account_summary_response_default as (
    "maker" double precision,
    "taker" double precision
);

comment on column deribit.private_get_account_summary_response_default."maker" is 'Maker fee';
comment on column deribit.private_get_account_summary_response_default."taker" is 'Taker fee';

create type deribit.private_get_account_summary_response_value as (
    "block_trade" double precision,
    "default" deribit.private_get_account_summary_response_default,
    "settlement" double precision
);

comment on column deribit.private_get_account_summary_response_value."block_trade" is 'Block trade fee (if applicable)';
comment on column deribit.private_get_account_summary_response_value."settlement" is 'Settlement fee';

create type deribit.private_get_account_summary_response_fee as (
    "index_name" text,
    "kind" text,
    "value" deribit.private_get_account_summary_response_value
);

comment on column deribit.private_get_account_summary_response_fee."index_name" is 'The currency pair this fee applies to';
comment on column deribit.private_get_account_summary_response_fee."kind" is 'Type of the instruments the fee applies to - future for future instruments (excluding perpetual), perpetual for future perpetual instruments, option for options';

create type deribit.private_get_account_summary_response_result as (
    "additional_reserve" double precision,
    "available_funds" double precision,
    "available_withdrawal_funds" double precision,
    "balance" double precision,
    "creation_timestamp" bigint,
    "cross_collateral_enabled" boolean,
    "currency" text,
    "delta_total" double precision,
    "deposit_address" text,
    "email" text,
    "equity" double precision,
    "estimated_liquidation_ratio" double precision,
    "fee_balance" double precision,
    "fee_group" text,
    "fees" deribit.private_get_account_summary_response_fee[],
    "futures_pl" double precision,
    "futures_session_rpl" double precision,
    "futures_session_upl" double precision,
    "has_non_block_chain_equity" boolean,
    "id" bigint,
    "initial_margin" double precision,
    "interuser_transfers_enabled" boolean,
    "limits" jsonb,
    "login_enabled" boolean,
    "maintenance_margin" double precision,
    "margin_balance" double precision,
    "margin_model" text,
    "mmp_enabled" boolean,
    "options_delta" double precision,
    "options_gamma" double precision,
    "options_gamma_map" jsonb,
    "options_pl" double precision,
    "options_session_rpl" double precision,
    "options_session_upl" double precision,
    "options_theta" double precision,
    "options_theta_map" jsonb,
    "options_value" double precision,
    "options_vega" double precision,
    "options_vega_map" jsonb,
    "portfolio_margining_enabled" boolean,
    "projected_delta_total" double precision,
    "projected_initial_margin" double precision,
    "projected_maintenance_margin" double precision,
    "referrer_id" text,
    "security_keys_enabled" boolean,
    "self_trading_extended_to_subaccounts" text,
    "self_trading_reject_mode" text,
    "session_rpl" double precision,
    "session_upl" double precision,
    "spot_reserve" double precision,
    "system_name" text,
    "total_delta_total_usd" double precision,
    "total_equity_usd" double precision,
    "total_initial_margin_usd" double precision,
    "total_maintenance_margin_usd" double precision,
    "total_margin_balance_usd" double precision,
    "total_pl" double precision,
    "username" text
);

comment on column deribit.private_get_account_summary_response_result."additional_reserve" is 'The account''s balance reserved in other orders';
comment on column deribit.private_get_account_summary_response_result."available_funds" is 'The account''s available funds. When cross collateral is enabled, this aggregated value is calculated by converting the sum of each cross collateral currency''s value to the given currency, using each cross collateral currency''s index.';
comment on column deribit.private_get_account_summary_response_result."available_withdrawal_funds" is 'The account''s available to withdrawal funds';
comment on column deribit.private_get_account_summary_response_result."balance" is 'The account''s balance';
comment on column deribit.private_get_account_summary_response_result."creation_timestamp" is 'Time at which the account was created (milliseconds since the Unix epoch; available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_result."cross_collateral_enabled" is 'When true cross collateral is enabled for user';
comment on column deribit.private_get_account_summary_response_result."currency" is 'The selected currency';
comment on column deribit.private_get_account_summary_response_result."delta_total" is 'The sum of position deltas';
comment on column deribit.private_get_account_summary_response_result."deposit_address" is 'The deposit address for the account (if available)';
comment on column deribit.private_get_account_summary_response_result."email" is 'User email (available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_result."equity" is 'The account''s current equity';
comment on column deribit.private_get_account_summary_response_result."estimated_liquidation_ratio" is 'Estimated Liquidation Ratio is returned only for users without portfolio margining enabled. Multiplying it by future position''s market price returns its estimated liquidation price. When cross collateral is enabled, this aggregated value is calculated by converting the sum of each cross collateral currency''s value to the given currency, using each cross collateral currency''s index.';
comment on column deribit.private_get_account_summary_response_result."fee_balance" is 'The account''s fee balance (it can be used to pay for fees)';
comment on column deribit.private_get_account_summary_response_result."fee_group" is 'Fee group indicates the level of fee discounts applied to an account. Use extended: true to view this field. If the field is missing, the account is not assigned to any fee group. 📖 Related Support Article: Automatically applied volume based fee discounts';
comment on column deribit.private_get_account_summary_response_result."fees" is 'List of fee objects for all currency pairs and instrument types related to the currency (available when parameter extended = true and user has any discounts)';
comment on column deribit.private_get_account_summary_response_result."futures_pl" is 'Futures profit and Loss';
comment on column deribit.private_get_account_summary_response_result."futures_session_rpl" is 'Futures session realized profit and Loss';
comment on column deribit.private_get_account_summary_response_result."futures_session_upl" is 'Futures session unrealized profit and Loss';
comment on column deribit.private_get_account_summary_response_result."has_non_block_chain_equity" is 'Optional field returned with value true when user has non block chain equity that is excluded from proof of reserve calculations';
comment on column deribit.private_get_account_summary_response_result."id" is 'Account id (available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_result."initial_margin" is 'The account''s initial margin. When cross collateral is enabled, this aggregated value is calculated by converting the sum of each cross collateral currency''s value to the given currency, using each cross collateral currency''s index.';
comment on column deribit.private_get_account_summary_response_result."interuser_transfers_enabled" is 'true when the inter-user transfers are enabled for user (available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_result."limits" is 'Returned object is described in separate document.';
comment on column deribit.private_get_account_summary_response_result."login_enabled" is 'Whether account is loginable using email and password (available when parameter extended = true and account is a subaccount)';
comment on column deribit.private_get_account_summary_response_result."maintenance_margin" is 'The maintenance margin. When cross collateral is enabled, this aggregated value is calculated by converting the sum of each cross collateral currency''s value to the given currency, using each cross collateral currency''s index.';
comment on column deribit.private_get_account_summary_response_result."margin_balance" is 'The account''s margin balance. When cross collateral is enabled, this aggregated value is calculated by converting the sum of each cross collateral currency''s value to the given currency, using each cross collateral currency''s index.';
comment on column deribit.private_get_account_summary_response_result."margin_model" is 'Name of user''s currently enabled margin model';
comment on column deribit.private_get_account_summary_response_result."mmp_enabled" is 'Whether MMP is enabled (available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_result."options_delta" is 'Options summary delta';
comment on column deribit.private_get_account_summary_response_result."options_gamma" is 'Options summary gamma';
comment on column deribit.private_get_account_summary_response_result."options_gamma_map" is 'Map of options'' gammas per index';
comment on column deribit.private_get_account_summary_response_result."options_pl" is 'Options profit and Loss';
comment on column deribit.private_get_account_summary_response_result."options_session_rpl" is 'Options session realized profit and Loss';
comment on column deribit.private_get_account_summary_response_result."options_session_upl" is 'Options session unrealized profit and Loss';
comment on column deribit.private_get_account_summary_response_result."options_theta" is 'Options summary theta';
comment on column deribit.private_get_account_summary_response_result."options_theta_map" is 'Map of options'' thetas per index';
comment on column deribit.private_get_account_summary_response_result."options_value" is 'Options value';
comment on column deribit.private_get_account_summary_response_result."options_vega" is 'Options summary vega';
comment on column deribit.private_get_account_summary_response_result."options_vega_map" is 'Map of options'' vegas per index';
comment on column deribit.private_get_account_summary_response_result."portfolio_margining_enabled" is 'true when portfolio margining is enabled for user';
comment on column deribit.private_get_account_summary_response_result."projected_delta_total" is 'The sum of position deltas without positions that will expire during closest expiration';
comment on column deribit.private_get_account_summary_response_result."projected_initial_margin" is 'Projected initial margin. When cross collateral is enabled, this aggregated value is calculated by converting the sum of each cross collateral currency''s value to the given currency, using each cross collateral currency''s index.';
comment on column deribit.private_get_account_summary_response_result."projected_maintenance_margin" is 'Projected maintenance margin. When cross collateral is enabled, this aggregated value is calculated by converting the sum of each cross collateral currency''s value to the given currency, using each cross collateral currency''s index.';
comment on column deribit.private_get_account_summary_response_result."referrer_id" is 'Optional identifier of the referrer (of the affiliation program, and available when parameter extended = true), which link was used by this account at registration. It coincides with suffix of the affiliation link path after /reg-';
comment on column deribit.private_get_account_summary_response_result."security_keys_enabled" is 'Whether Security Key authentication is enabled (available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_result."self_trading_extended_to_subaccounts" is 'true if self trading rejection behavior is applied to trades between subaccounts (available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_result."self_trading_reject_mode" is 'Self trading rejection behavior - reject_taker or cancel_maker (available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_result."session_rpl" is 'Session realized profit and loss';
comment on column deribit.private_get_account_summary_response_result."session_upl" is 'Session unrealized profit and loss';
comment on column deribit.private_get_account_summary_response_result."spot_reserve" is 'The account''s balance reserved in active spot orders';
comment on column deribit.private_get_account_summary_response_result."system_name" is 'System generated user nickname (available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_result."total_delta_total_usd" is 'Optional (only for users using cross margin). The account''s total delta total in all cross collateral currencies, expressed in USD';
comment on column deribit.private_get_account_summary_response_result."total_equity_usd" is 'Optional (only for users using cross margin). The account''s total equity in all cross collateral currencies, expressed in USD';
comment on column deribit.private_get_account_summary_response_result."total_initial_margin_usd" is 'Optional (only for users using cross margin). The account''s total initial margin in all cross collateral currencies, expressed in USD';
comment on column deribit.private_get_account_summary_response_result."total_maintenance_margin_usd" is 'Optional (only for users using cross margin). The account''s total maintenance margin in all cross collateral currencies, expressed in USD';
comment on column deribit.private_get_account_summary_response_result."total_margin_balance_usd" is 'Optional (only for users using cross margin). The account''s total margin balance in all cross collateral currencies, expressed in USD';
comment on column deribit.private_get_account_summary_response_result."total_pl" is 'Profit and loss';
comment on column deribit.private_get_account_summary_response_result."username" is 'Account name (given by user) (available when parameter extended = true)';

create type deribit.private_get_account_summary_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" deribit.private_get_account_summary_response_result
);

comment on column deribit.private_get_account_summary_response."id" is 'The id that was sent in the request';
comment on column deribit.private_get_account_summary_response."jsonrpc" is 'The JSON-RPC version (2.0)';

create function deribit.private_get_account_summary(
    "currency" deribit.private_get_account_summary_request_currency,
    "subaccount_id" bigint default null,
    "extended" boolean default null
)
returns deribit.private_get_account_summary_response_result
language sql
as $$
    
    with request as (
        select row(
            "currency",
            "subaccount_id",
            "extended"
        )::deribit.private_get_account_summary_request as payload
    ), 
    http_response as (
        select deribit.private_jsonrpc_request(
            auth := deribit.get_auth(),
            url := '/private/get_account_summary'::deribit.endpoint,
            request := request.payload,
            rate_limiter := 'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
        from request
    )
    select (
        jsonb_populate_record(
            null::deribit.private_get_account_summary_response,
            convert_from((a.http_response).body, 'utf-8')::jsonb
        )
    ).result
    from http_response a

$$;

comment on function deribit.private_get_account_summary is 'Retrieves user account summary. To read subaccount summary use subaccount_id parameter.';
