/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.private_cancel_by_label_request_currency as enum (
    'BTC',
    'ETH',
    'EURR',
    'USDC',
    'USDT'
);

create type deribit.private_cancel_by_label_request as (
    "label" text,
    "currency" deribit.private_cancel_by_label_request_currency
);

comment on column deribit.private_cancel_by_label_request."label" is '(Required) user defined label for the order (maximum 64 characters)';
comment on column deribit.private_cancel_by_label_request."currency" is 'The currency symbol';

create type deribit.private_cancel_by_label_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" double precision
);

comment on column deribit.private_cancel_by_label_response."id" is 'The id that was sent in the request';
comment on column deribit.private_cancel_by_label_response."jsonrpc" is 'The JSON-RPC version (2.0)';
comment on column deribit.private_cancel_by_label_response."result" is 'Total number of successfully cancelled orders';

create function deribit.private_cancel_by_label(
    "label" text,
    "currency" deribit.private_cancel_by_label_request_currency default null
)
returns double precision
language sql
as $$
    
    with request as (
        select row(
            "label",
            "currency"
        )::deribit.private_cancel_by_label_request as payload
    ), 
    http_response as (
        select deribit.private_jsonrpc_request(
            auth := deribit.get_auth(),
            url := '/private/cancel_by_label'::deribit.endpoint,
            request := request.payload,
            rate_limiter := 'deribit.matching_engine_request_log_call'::name
        ) as http_response
        from request
    )
    select (
        jsonb_populate_record(
            null::deribit.private_cancel_by_label_response,
            convert_from((a.http_response).body, 'utf-8')::jsonb
        )
    ).result
    from http_response a

$$;

comment on function deribit.private_cancel_by_label is 'Cancels orders by label. All user''s orders (trigger orders too), with a given label are cancelled in all currencies or in one given currency (in this case currency queue is used) ';
