/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.private_reset_mmp_request as (
    "index_name" text,
    "mmp_group" text,
    "block_rfq" boolean
);

comment on column deribit.private_reset_mmp_request."index_name" is '(Required) Currency pair for which to reset MMP limits.  For regular MMP (block_rfq = false): Must be a specific currency pair (e.g., "btc_usd", "eth_usd"). The value "all" is not allowed.  For Block RFQ MMP (block_rfq = true): Can be either a specific currency pair or "all" to reset MMP limits across all currency pairs.';
comment on column deribit.private_reset_mmp_request."mmp_group" is 'Specifies the MMP group for which limits are being reset. If this parameter is omitted, the method resets the traditional (no group) MMP limits. 📖 Related Support Article: Mass Quotes Specifications';
comment on column deribit.private_reset_mmp_request."block_rfq" is 'If true, resets MMP for Block RFQ. When set, requires block_rfq scope instead of trade scope. Block RFQ MMP settings are completely separate from normal order/quote MMP settings. When block_rfq = true, the index_name parameter can be set to "all" to reset limits across all currency pairs.';

create type deribit.private_reset_mmp_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" text
);

comment on column deribit.private_reset_mmp_response."id" is 'The id that was sent in the request';
comment on column deribit.private_reset_mmp_response."jsonrpc" is 'The JSON-RPC version (2.0)';
comment on column deribit.private_reset_mmp_response."result" is 'Result of method execution. ok in case of success';

create function deribit.private_reset_mmp(
    "index_name" text,
    "mmp_group" text default null,
    "block_rfq" boolean default null
)
returns text
language sql
as $$
    
    with request as (
        select row(
            "index_name",
            "mmp_group",
            "block_rfq"
        )::deribit.private_reset_mmp_request as payload
    ), 
    http_response as (
        select deribit.private_jsonrpc_request(
            auth := deribit.get_auth(),
            url := '/private/reset_mmp'::deribit.endpoint,
            request := request.payload,
            rate_limiter := 'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
        from request
    )
    select (
        jsonb_populate_record(
            null::deribit.private_reset_mmp_response,
            convert_from((a.http_response).body, 'utf-8')::jsonb
        )
    ).result
    from http_response a

$$;

comment on function deribit.private_reset_mmp is 'Reset Market Maker Protection (MMP) limits for the specified currency pair or group.

📖 Related Support Article: Market Maker Protection API Configuration';
