/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.public_get_funding_chart_data_request_length as enum (
    '1m',
    '24h',
    '8h'
);

create type deribit.public_get_funding_chart_data_request as (
    "instrument_name" text,
    "length" deribit.public_get_funding_chart_data_request_length
);

comment on column deribit.public_get_funding_chart_data_request."instrument_name" is '(Required) Instrument name';
comment on column deribit.public_get_funding_chart_data_request."length" is '(Required) Specifies time period. 8h - 8 hours, 24h - 24 hours, 1m - 1 month';

create type deribit.public_get_funding_chart_data_response_datum as (
    "index_price" double precision,
    "interest_8h" double precision,
    "timestamp" bigint
);

comment on column deribit.public_get_funding_chart_data_response_datum."index_price" is 'Current index price';
comment on column deribit.public_get_funding_chart_data_response_datum."interest_8h" is 'Historical interest 8h value';
comment on column deribit.public_get_funding_chart_data_response_datum."timestamp" is 'The timestamp (milliseconds since the Unix epoch)';

create type deribit.public_get_funding_chart_data_response_result as (
    "current_interest" double precision,
    "data" deribit.public_get_funding_chart_data_response_datum[],
    "interest_8h" double precision
);

comment on column deribit.public_get_funding_chart_data_response_result."current_interest" is 'Current interest';
comment on column deribit.public_get_funding_chart_data_response_result."interest_8h" is 'Current interest 8h';

create type deribit.public_get_funding_chart_data_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" deribit.public_get_funding_chart_data_response_result
);

comment on column deribit.public_get_funding_chart_data_response."id" is 'The id that was sent in the request';
comment on column deribit.public_get_funding_chart_data_response."jsonrpc" is 'The JSON-RPC version (2.0)';

create function deribit.public_get_funding_chart_data(
    "instrument_name" text,
    "length" deribit.public_get_funding_chart_data_request_length
)
returns deribit.public_get_funding_chart_data_response_result
language sql
as $$
    
    with request as (
        select row(
            "instrument_name",
            "length"
        )::deribit.public_get_funding_chart_data_request as payload
    ), 
    http_response as (
        select deribit.public_jsonrpc_request(
            url := '/public/get_funding_chart_data'::deribit.endpoint,
            request := request.payload,
            rate_limiter := 'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
        from request
    )
    select (
        jsonb_populate_record(
            null::deribit.public_get_funding_chart_data_response,
            convert_from((a.http_response).body, 'utf-8')::jsonb
        )
    ).result
    from http_response a

$$;

comment on function deribit.public_get_funding_chart_data is 'Retrieve the list of the latest PERPETUAL funding chart points within a given time period.';
