/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.public_get_order_book_request_depth as enum (
    '1',
    '10',
    '100',
    '1000',
    '10000',
    '20',
    '5',
    '50'
);

create type deribit.public_get_order_book_request as (
    "instrument_name" text,
    "depth" deribit.public_get_order_book_request_depth
);

comment on column deribit.public_get_order_book_request."instrument_name" is '(Required) The instrument name for which to retrieve the order book, see public/get_instruments to obtain instrument names.';
comment on column deribit.public_get_order_book_request."depth" is 'The number of entries to return for bids and asks, maximum - 10000.';

create type deribit.public_get_order_book_response_error as (
    "code" bigint,
    "message" text
);

comment on column deribit.public_get_order_book_response_error."code" is 'Error code';
comment on column deribit.public_get_order_book_response_error."message" is 'Error message';

create type deribit.public_get_order_book_response_result as (
    "error" deribit.public_get_order_book_response_error,
    "jsonrpc" text
);

create type deribit.public_get_order_book_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" deribit.public_get_order_book_response_result
);

comment on column deribit.public_get_order_book_response."id" is 'The id that was sent in the request';
comment on column deribit.public_get_order_book_response."jsonrpc" is 'The JSON-RPC version (2.0)';
comment on column deribit.public_get_order_book_response."result" is 'Generic error response for broken references';

create function deribit.public_get_order_book(
    "instrument_name" text,
    "depth" deribit.public_get_order_book_request_depth default null
)
returns deribit.public_get_order_book_response_result
language sql
as $$
    
    with request as (
        select row(
            "instrument_name",
            "depth"
        )::deribit.public_get_order_book_request as payload
    ), 
    http_response as (
        select deribit.public_jsonrpc_request(
            url := '/public/get_order_book'::deribit.endpoint,
            request := request.payload,
            rate_limiter := 'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
        from request
    )
    select (
        jsonb_populate_record(
            null::deribit.public_get_order_book_response,
            convert_from((a.http_response).body, 'utf-8')::jsonb
        )
    ).result
    from http_response a

$$;

comment on function deribit.public_get_order_book is 'Retrieves the order book, along with other market values for a given instrument.';
