/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.public_get_volatility_index_data_request_currency as enum (
    'BTC',
    'ETH',
    'EURR',
    'USDC',
    'USDT'
);

create type deribit.public_get_volatility_index_data_request_resolution as enum (
    '1',
    '1D',
    '3600',
    '43200',
    '60'
);

create type deribit.public_get_volatility_index_data_request as (
    "currency" deribit.public_get_volatility_index_data_request_currency,
    "start_timestamp" bigint,
    "end_timestamp" bigint,
    "resolution" deribit.public_get_volatility_index_data_request_resolution
);

comment on column deribit.public_get_volatility_index_data_request."currency" is '(Required) The currency symbol';
comment on column deribit.public_get_volatility_index_data_request."start_timestamp" is '(Required) The earliest timestamp to return result from (milliseconds since the UNIX epoch)';
comment on column deribit.public_get_volatility_index_data_request."end_timestamp" is '(Required) The most recent timestamp to return result from (milliseconds since the UNIX epoch)';
comment on column deribit.public_get_volatility_index_data_request."resolution" is '(Required) Time resolution given in full seconds or keyword 1D (only some specific resolutions are supported)';

create type deribit.public_get_volatility_index_data_response_result as (
    "continuation" bigint,
    "data" text[]
);

comment on column deribit.public_get_volatility_index_data_response_result."continuation" is 'Continuation - to be used as the end_timestamp parameter on the next request. NULL when no continuation.';
comment on column deribit.public_get_volatility_index_data_response_result."data" is 'Candles as an array of arrays with 5 values each. The inner values correspond to the timestamp in ms, open, high, low, and close values of the volatility index correspondingly.';

create type deribit.public_get_volatility_index_data_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" deribit.public_get_volatility_index_data_response_result
);

comment on column deribit.public_get_volatility_index_data_response."id" is 'The id that was sent in the request';
comment on column deribit.public_get_volatility_index_data_response."jsonrpc" is 'The JSON-RPC version (2.0)';
comment on column deribit.public_get_volatility_index_data_response."result" is 'Volatility index candles.';

create function deribit.public_get_volatility_index_data(    "currency" deribit.public_get_volatility_index_data_request_currency,
    "start_timestamp" bigint,
    "end_timestamp" bigint,
    "resolution" deribit.public_get_volatility_index_data_request_resolution
)
returns deribit.public_get_volatility_index_data_response_result
language sql
as $$
    
    with request as (
        select row(
            "currency",
            "start_timestamp",
            "end_timestamp",
            "resolution"
        )::deribit.public_get_volatility_index_data_request as payload
    ), 
    http_response as (
        select deribit.public_jsonrpc_request(            
            url := '/public/get_volatility_index_data'::deribit.endpoint, 
            request := request.payload, 
            rate_limiter := 'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
        from request
    )
    select (jsonb_populate_record(
        null::deribit.public_get_volatility_index_data_response, 
        convert_from((a.http_response).body, 'utf-8')::jsonb)).result
    from http_response a

$$;

comment on function deribit.public_get_volatility_index_data is 'Public market data request for volatility index candles.';
