/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.public_get_supported_index_names_request_type as enum (
    'all',
    'derivative',
    'spot'
);

create type deribit.public_get_supported_index_names_request as (
    "type" deribit.public_get_supported_index_names_request_type
);

comment on column deribit.public_get_supported_index_names_request."type" is 'Type of a cryptocurrency price index';

create type deribit.public_get_supported_index_names_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" text[]
);

comment on column deribit.public_get_supported_index_names_response."id" is 'The id that was sent in the request';
comment on column deribit.public_get_supported_index_names_response."jsonrpc" is 'The JSON-RPC version (2.0)';

create function deribit.public_get_supported_index_names(
    "type" deribit.public_get_supported_index_names_request_type default null
)
returns setof text
language sql
as $$
    
    with request as (
        select row(
            "type"
        )::deribit.public_get_supported_index_names_request as payload
    ), 
    http_response as (
        select deribit.public_jsonrpc_request(
            url := '/public/get_supported_index_names'::deribit.endpoint,
            request := request.payload,
            rate_limiter := 'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
        from request
    ),
    result as (
        select (jsonb_populate_record(
            null::deribit.public_get_supported_index_names_response,
            convert_from((http_response.http_response).body, 'utf-8')::jsonb)
        ).result
        from http_response
    )
    select
        a.b
    from (
        select (unnest(r.data)) b
        from result r(data)
    ) a
    
$$;

comment on function deribit.public_get_supported_index_names is 'Retrieves the identifiers of all supported Price Indexes';
