/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
create type deribit.public_get_announcements_request as (
    "start_timestamp" bigint,
    "count" bigint
);

comment on column deribit.public_get_announcements_request."start_timestamp" is 'The most recent timestamp to return the results for (milliseconds since the UNIX epoch)';
comment on column deribit.public_get_announcements_request."count" is 'Maximum count of returned announcements';

create type deribit.public_get_announcements_response_result as (
    "body" text,
    "confirmation" boolean,
    "id" double precision,
    "important" boolean,
    "publication_timestamp" bigint,
    "title" text
);

comment on column deribit.public_get_announcements_response_result."body" is 'The HTML body of the announcement';
comment on column deribit.public_get_announcements_response_result."confirmation" is 'Whether the user confirmation is required for this announcement';
comment on column deribit.public_get_announcements_response_result."id" is 'A unique identifier for the announcement';
comment on column deribit.public_get_announcements_response_result."important" is 'Whether the announcement is marked as important';
comment on column deribit.public_get_announcements_response_result."publication_timestamp" is 'The timestamp (milliseconds since the Unix epoch) of announcement publication';
comment on column deribit.public_get_announcements_response_result."title" is 'The title of the announcement';

create type deribit.public_get_announcements_response as (
    "id" bigint,
    "jsonrpc" text,
    "result" deribit.public_get_announcements_response_result[]
);

comment on column deribit.public_get_announcements_response."id" is 'The id that was sent in the request';
comment on column deribit.public_get_announcements_response."jsonrpc" is 'The JSON-RPC version (2.0)';

create function deribit.public_get_announcements(
    "start_timestamp" bigint default null,
    "count" bigint default null
)
returns setof deribit.public_get_announcements_response_result
language sql
as $$
    
    with request as (
        select row(
            "start_timestamp",
            "count"
        )::deribit.public_get_announcements_request as payload
    ), 
    http_response as (
        select deribit.public_jsonrpc_request(
            url := '/public/get_announcements'::deribit.endpoint,
            request := request.payload,
            rate_limiter := 'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
        from request
    ),
    result as (
        select (jsonb_populate_record(
            null::deribit.public_get_announcements_response,
            convert_from((http_response.http_response).body, 'utf-8')::jsonb)
        ).result
        from http_response
    )
    select
        (b)."body"::text,
        (b)."confirmation"::boolean,
        (b)."id"::double precision,
        (b)."important"::boolean,
        (b)."publication_timestamp"::bigint,
        (b)."title"::text
    from (
        select (unnest(r.data)) b
        from result r(data)
    ) a
    
$$;

comment on function deribit.public_get_announcements is 'Retrieves announcements. Default "start_timestamp" parameter value is current timestamp, "count" parameter value must be between 1 and 50, default is 5.';
