/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop function if exists deribit.public_get_combos;

create or replace function deribit.public_get_combos(
    currency deribit.public_get_combos_request_currency
)
returns setof deribit.public_get_combos_response_result
language sql
as $$
    
    with request as (
        select row(
            currency
        )::deribit.public_get_combos_request as payload
    )
    , http_response as (
        select deribit.internal_jsonrpc_request(
            '/public/get_combos'::deribit.endpoint, 
            request.payload, 
            'deribit.non_matching_engine_request_log_call'::name
        ) as http_response
        from request
    )
    , result as (
        select (jsonb_populate_record(
                        null::deribit.public_get_combos_response,
                        convert_from((http_response.http_response).body, 'utf-8')::jsonb)
             ).result
        from http_response
    )
    select
        (b).creation_timestamp::bigint,
        (b).id::text,
        (b).instrument_id::bigint,
        (b).legs::deribit.public_get_combos_response_leg[],
        (b).state::text,
        (b).state_timestamp::bigint
    from (
        select (unnest(r.data)) b
        from result r(data)
    ) a
    
$$;

comment on function deribit.public_get_combos is 'Retrieves information about active combos';
