import os

from codegen.models.models import Function
from codegen.postgres.enum import enum_to_type
from codegen.postgres.postgres import invoke_endpoint, type_to_type
from codegen.postgres.tests import test_endpoint


class Exporter:

    def __init__(self):
        self.schema = None
        self.script_dir = os.path.dirname(__file__)

    def set_schema(self, schema: str):
        self.schema = schema

    def setup(self):
        with open(os.path.join(self.script_dir, f"../../test/all_functions.gen.sql"), 'w') as file:
            file.write(header())
            pass
        pass

    def sort_functions(self, functions: [Function]):
        return sorted(functions, key=lambda f: f.endpoint.name)

    def all(self, functions: [Function]):
        self.setup()

        for function in self.sort_functions(functions):
            self.export(function)

        with open(os.path.join(self.script_dir, f"../../sql/types/endpoints.gen.sql"), 'w') as file:
            file.write(header())
            file.write(f"drop type if exists deribit.endpoint cascade;\n")
            file.write(f"create type deribit.endpoint as enum (\n")
            file.write(f',\n'.join(f"\t'{function.endpoint.path}'" for function in functions))
            file.write(f"\n);")

        with open(os.path.join(self.script_dir, f"../../sql/static/endpoints.gen.sql"), 'w') as file:
            file.write(header())
            file.write(f"""insert into deribit.internal_endpoint_rate_limit (key)\nvalues\n""")
            file.write(f',\n'.join(f"\t('{function.endpoint.path}')" for function in functions))
            file.write(';\n')

    def export(self, function: Function):
        script_dir = os.path.dirname(__file__)

        with open(os.path.join(script_dir, f"../../sql/types/{function.endpoint.name}.gen.sql"), 'w') as file:
            file.write(header())

            for tpe in reversed(function.endpoint.response_types):
                file.write(type_to_type(self.schema, tpe))
                file.write('\n\n')

            if function.endpoint.request_type is not None:
                for enum in function.endpoint.request_type.enums:
                    file.write(enum_to_type(self.schema, function.endpoint.request_type.name, enum))
                    file.write('\n\n')

                file.write(type_to_type(self.schema, function.endpoint.request_type))
                file.write('\n\n')

        with open(os.path.join(script_dir, f"../../sql/functions/{function.endpoint.name}.gen.sql"), 'w') as file:
            file.write(header())
            file.write(invoke_endpoint(self.schema, function))
            file.write('\n\n')

        with open(os.path.join(script_dir, f"../../test/all_functions.gen.sql"), 'a') as file:
            file.write(test_endpoint(self.schema, function))
            file.write('\n\n')


def header() -> str:
    return """/*
 * AUTO-GENERATED FILE - DO NOT MODIFY
 * 
 * This SQL file was generated by a code generation tool. Any modifications
 * made to this file may be overwritten by subsequent code generation
 * processes and could lead to inconsistencies or errors in the application.
 * 
 * For any required changes, please modify the source templates or the
 * code generation tool's configurations and regenerate this file.
 *
 * WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
 * AND IS STRONGLY DISCOURAGED.
 */
 """