/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.private_get_account_summary_request_currency cascade;

create type deribit.private_get_account_summary_request_currency as enum (
    'BTC',
    'ETH',
    'USDC',
    'USDT'
);

drop type if exists deribit.private_get_account_summary_request cascade;

create type deribit.private_get_account_summary_request as (
    currency deribit.private_get_account_summary_request_currency,
    subaccount_id bigint,
    extended boolean
);

comment on column deribit.private_get_account_summary_request.currency is '(Required) The currency symbol';
comment on column deribit.private_get_account_summary_request.subaccount_id is 'The user id for the subaccount';
comment on column deribit.private_get_account_summary_request.extended is 'Include additional fields';
