/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.private_cancel_by_label_request_currency cascade;

create type deribit.private_cancel_by_label_request_currency as enum (
    'BTC',
    'ETH',
    'USDC',
    'USDT'
);

drop type if exists deribit.private_cancel_by_label_request cascade;

create type deribit.private_cancel_by_label_request as (
    label text,
    currency deribit.private_cancel_by_label_request_currency
);

comment on column deribit.private_cancel_by_label_request.label is '(Required) user defined label for the order (maximum 64 characters)';
comment on column deribit.private_cancel_by_label_request.currency is 'The currency symbol';
