/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.private_create_subaccount_response_eth cascade;

create type deribit.private_create_subaccount_response_eth as (
    available_funds double precision,
    available_withdrawal_funds double precision,
    balance double precision,
    currency text,
    equity double precision,
    initial_margin double precision,
    maintenance_margin double precision,
    margin_balance double precision
);



drop type if exists deribit.private_create_subaccount_response_btc cascade;

create type deribit.private_create_subaccount_response_btc as (
    available_funds double precision,
    available_withdrawal_funds double precision,
    balance double precision,
    currency text,
    equity double precision,
    initial_margin double precision,
    maintenance_margin double precision,
    margin_balance double precision
);



drop type if exists deribit.private_create_subaccount_response_portfolio cascade;

create type deribit.private_create_subaccount_response_portfolio as (
    btc deribit.private_create_subaccount_response_btc,
    eth deribit.private_create_subaccount_response_eth,
    receive_notifications boolean,
    security_keys_enabled boolean,
    system_name text,
    type text,
    username text
);

comment on column deribit.private_create_subaccount_response_portfolio.receive_notifications is 'When true - receive all notification emails on the main email';
comment on column deribit.private_create_subaccount_response_portfolio.security_keys_enabled is 'Whether the Security Keys authentication is enabled';
comment on column deribit.private_create_subaccount_response_portfolio.system_name is 'System generated user nickname';
comment on column deribit.private_create_subaccount_response_portfolio.type is 'Account type';
comment on column deribit.private_create_subaccount_response_portfolio.username is 'Account name (given by user)';

drop type if exists deribit.private_create_subaccount_response_result cascade;

create type deribit.private_create_subaccount_response_result as (
    email text,
    id bigint,
    is_password boolean,
    login_enabled boolean,
    portfolio deribit.private_create_subaccount_response_portfolio
);

comment on column deribit.private_create_subaccount_response_result.email is 'User email';
comment on column deribit.private_create_subaccount_response_result.id is 'Subaccount identifier';
comment on column deribit.private_create_subaccount_response_result.is_password is 'true when password for the subaccount has been configured';
comment on column deribit.private_create_subaccount_response_result.login_enabled is 'Informs whether login to the subaccount is enabled';

drop type if exists deribit.private_create_subaccount_response cascade;

create type deribit.private_create_subaccount_response as (
    id bigint,
    jsonrpc text,
    result deribit.private_create_subaccount_response_result
);

comment on column deribit.private_create_subaccount_response.id is 'The id that was sent in the request';
comment on column deribit.private_create_subaccount_response.jsonrpc is 'The JSON-RPC version (2.0)';

