/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.private_change_margin_model_response_old_state cascade;

create type deribit.private_change_margin_model_response_old_state as (
    available_balance double precision,
    initial_margin_rate double precision,
    maintenance_margin_rate double precision
);

comment on column deribit.private_change_margin_model_response_old_state.available_balance is 'Available balance before change';
comment on column deribit.private_change_margin_model_response_old_state.initial_margin_rate is 'Initial margin rate before change';
comment on column deribit.private_change_margin_model_response_old_state.maintenance_margin_rate is 'Maintenance margin rate before change';

drop type if exists deribit.private_change_margin_model_response_new_state cascade;

create type deribit.private_change_margin_model_response_new_state as (
    available_balance double precision,
    initial_margin_rate double precision,
    maintenance_margin_rate double precision
);

comment on column deribit.private_change_margin_model_response_new_state.available_balance is 'Available balance after change';
comment on column deribit.private_change_margin_model_response_new_state.initial_margin_rate is 'Initial margin rate after change';
comment on column deribit.private_change_margin_model_response_new_state.maintenance_margin_rate is 'Maintenance margin rate after change';

drop type if exists deribit.private_change_margin_model_response_result cascade;

create type deribit.private_change_margin_model_response_result as (
    currency text,
    new_state deribit.private_change_margin_model_response_new_state,
    old_state deribit.private_change_margin_model_response_old_state
);

comment on column deribit.private_change_margin_model_response_result.currency is 'Currency, i.e "BTC", "ETH", "USDC"';
comment on column deribit.private_change_margin_model_response_result.new_state is 'Represents portfolio state after change';
comment on column deribit.private_change_margin_model_response_result.old_state is 'Represents portfolio state before change';

drop type if exists deribit.private_change_margin_model_response cascade;

create type deribit.private_change_margin_model_response as (
    id bigint,
    jsonrpc text,
    result deribit.private_change_margin_model_response_result[]
);

comment on column deribit.private_change_margin_model_response.id is 'The id that was sent in the request';
comment on column deribit.private_change_margin_model_response.jsonrpc is 'The JSON-RPC version (2.0)';

