/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.private_reset_mmp_response cascade;

create type deribit.private_reset_mmp_response as (
    id bigint,
    jsonrpc text,
    result text
);

comment on column deribit.private_reset_mmp_response.id is 'The id that was sent in the request';
comment on column deribit.private_reset_mmp_response.jsonrpc is 'The JSON-RPC version (2.0)';
comment on column deribit.private_reset_mmp_response.result is 'Result of method execution. ok in case of success';

drop type if exists deribit.private_reset_mmp_request_index_name cascade;

create type deribit.private_reset_mmp_request_index_name as enum (
    'ada_usdc',
    'algo_usdc',
    'avax_usdc',
    'bch_usdc',
    'bnb_usdc',
    'btc_usd',
    'btc_usdc',
    'btcdvol_usdc',
    'doge_usdc',
    'dot_usdc',
    'eth_usd',
    'eth_usdc',
    'ethdvol_usdc',
    'link_usdc',
    'ltc_usdc',
    'luna_usdc',
    'matic_usdc',
    'mshib_usdc',
    'near_usdc',
    'shib_usdc',
    'trx_usdc',
    'uni_usdc',
    'xrp_usdc'
);

drop type if exists deribit.private_reset_mmp_request cascade;

create type deribit.private_reset_mmp_request as (
    index_name deribit.private_reset_mmp_request_index_name
);

comment on column deribit.private_reset_mmp_request.index_name is '(Required) Index identifier of derivative instrument on the platform';
