/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.private_remove_api_key_response cascade;

create type deribit.private_remove_api_key_response as (
    id bigint,
    jsonrpc text,
    result text
);

comment on column deribit.private_remove_api_key_response.id is 'The id that was sent in the request';
comment on column deribit.private_remove_api_key_response.jsonrpc is 'The JSON-RPC version (2.0)';
comment on column deribit.private_remove_api_key_response.result is 'Result of method execution. ok in case of success';

drop type if exists deribit.private_remove_api_key_request cascade;

create type deribit.private_remove_api_key_request as (
    id bigint
);

comment on column deribit.private_remove_api_key_request.id is '(Required) Id of key';
