/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.private_unsubscribe_response cascade;

create type deribit.private_unsubscribe_response as (
    id bigint,
    jsonrpc text,
    result text[]
);

comment on column deribit.private_unsubscribe_response.id is 'The id that was sent in the request';
comment on column deribit.private_unsubscribe_response.jsonrpc is 'The JSON-RPC version (2.0)';
comment on column deribit.private_unsubscribe_response.result is 'A list of subscribed channels.';

drop type if exists deribit.private_unsubscribe_request cascade;

create type deribit.private_unsubscribe_request as (
    channels text[]
);

comment on column deribit.private_unsubscribe_request.channels is '(Required) A list of channels to unsubscribe from.';
