/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.private_get_order_history_by_currency_request_currency cascade;

create type deribit.private_get_order_history_by_currency_request_currency as enum (
    'BTC',
    'ETH',
    'USDC',
    'USDT'
);

drop type if exists deribit.private_get_order_history_by_currency_request_kind cascade;

create type deribit.private_get_order_history_by_currency_request_kind as enum (
    'any',
    'combo',
    'future',
    'future_combo',
    'option',
    'option_combo',
    'spot'
);

drop type if exists deribit.private_get_order_history_by_currency_request cascade;

create type deribit.private_get_order_history_by_currency_request as (
    currency deribit.private_get_order_history_by_currency_request_currency,
    kind deribit.private_get_order_history_by_currency_request_kind,
    count bigint,
    "offset" bigint,
    include_old boolean,
    include_unfilled boolean
);

comment on column deribit.private_get_order_history_by_currency_request.currency is '(Required) The currency symbol';
comment on column deribit.private_get_order_history_by_currency_request.kind is 'Instrument kind, "combo" for any combo or "any" for all. If not provided instruments of all kinds are considered';
comment on column deribit.private_get_order_history_by_currency_request.count is 'Number of requested items, default - 20';
comment on column deribit.private_get_order_history_by_currency_request."offset" is 'The offset for pagination, default - 0';
comment on column deribit.private_get_order_history_by_currency_request.include_old is 'Include in result orders older than 2 days, default - false';
comment on column deribit.private_get_order_history_by_currency_request.include_unfilled is 'Include in result fully unfilled closed orders, default - false';
