/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.private_set_mmp_config_response_result cascade;

create type deribit.private_set_mmp_config_response_result as (
    delta_limit double precision,
    frozen_time bigint,
    index_name text,
    "interval" bigint,
    quantity_limit double precision
);

comment on column deribit.private_set_mmp_config_response_result.delta_limit is 'Delta limit';
comment on column deribit.private_set_mmp_config_response_result.frozen_time is 'MMP frozen time in seconds, if set to 0 manual reset is required';
comment on column deribit.private_set_mmp_config_response_result.index_name is 'Index identifier, matches (base) cryptocurrency with quote currency';
comment on column deribit.private_set_mmp_config_response_result."interval" is 'MMP Interval in seconds, if set to 0 MMP is disabled';
comment on column deribit.private_set_mmp_config_response_result.quantity_limit is 'Quantity limit';

drop type if exists deribit.private_set_mmp_config_response cascade;

create type deribit.private_set_mmp_config_response as (
    id bigint,
    jsonrpc text,
    result deribit.private_set_mmp_config_response_result[]
);

comment on column deribit.private_set_mmp_config_response.id is 'The id that was sent in the request';
comment on column deribit.private_set_mmp_config_response.jsonrpc is 'The JSON-RPC version (2.0)';

