/*
 * AUTO-GENERATED FILE - DO NOT MODIFY
 * 
 * This SQL file was generated by a code generation tool. Any modifications
 * made to this file may be overwritten by subsequent code generation
 * processes and could lead to inconsistencies or errors in the application.
 * 
 * For any required changes, please modify the source templates or the
 * code generation tool's configurations and regenerate this file.
 *
 * WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
 * AND IS STRONGLY DISCOURAGED.
 */
 drop type if exists deribit.private_get_account_summary_response_options_theta_map cascade;
create type deribit.private_get_account_summary_response_options_theta_map as (
	creation_timestamp bigint,
	available_withdrawal_funds double precision,
	equity double precision,
	options_gamma double precision
);
comment on column deribit.private_get_account_summary_response_options_theta_map.creation_timestamp is 'Time at which the account was created (milliseconds since the Unix epoch; available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_options_theta_map.available_withdrawal_funds is 'The account''s available to withdrawal funds';
comment on column deribit.private_get_account_summary_response_options_theta_map.equity is 'The account''s current equity';
comment on column deribit.private_get_account_summary_response_options_theta_map.options_gamma is 'Options summary gamma';

drop type if exists deribit.private_get_account_summary_response_options_vega_map cascade;
create type deribit.private_get_account_summary_response_options_vega_map as (
	balance double precision,
	mmp_enabled boolean,
	projected_initial_margin double precision,
	email text,
	available_funds double precision,
	spot_reserve double precision,
	projected_delta_total double precision,
	portfolio_margining_enabled boolean,
	total_pl double precision,
	margin_balance double precision,
	options_theta_map deribit.private_get_account_summary_response_options_theta_map
);
comment on column deribit.private_get_account_summary_response_options_vega_map.balance is 'The account''s balance';
comment on column deribit.private_get_account_summary_response_options_vega_map.mmp_enabled is 'Whether MMP is enabled (available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_options_vega_map.projected_initial_margin is 'Projected initial margin';
comment on column deribit.private_get_account_summary_response_options_vega_map.email is 'User email (available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_options_vega_map.available_funds is 'The account''s available funds';
comment on column deribit.private_get_account_summary_response_options_vega_map.spot_reserve is 'The account''s balance reserved in active spot orders';
comment on column deribit.private_get_account_summary_response_options_vega_map.projected_delta_total is 'The sum of position deltas without positions that will expire during closest expiration';
comment on column deribit.private_get_account_summary_response_options_vega_map.portfolio_margining_enabled is 'true when portfolio margining is enabled for user';
comment on column deribit.private_get_account_summary_response_options_vega_map.total_pl is 'Profit and loss';
comment on column deribit.private_get_account_summary_response_options_vega_map.margin_balance is 'The account''s margin balance';
comment on column deribit.private_get_account_summary_response_options_vega_map.options_theta_map is 'Map of options'' thetas per index';

drop type if exists deribit.private_get_account_summary_response_options_gamma_map cascade;
create type deribit.private_get_account_summary_response_options_gamma_map as (
	futures_pl double precision,
	currency text,
	options_value double precision,
	security_keys_enabled boolean,
	self_trading_extended_to_subaccounts text,
	projected_maintenance_margin double precision,
	options_vega double precision,
	session_rpl double precision,
	has_non_block_chain_equity boolean,
	system_name text,
	deposit_address text,
	futures_session_upl double precision,
	options_session_upl double precision,
	referrer_id text,
	options_theta double precision,
	login_enabled boolean,
	username text,
	interuser_transfers_enabled boolean,
	options_delta double precision,
	options_pl double precision,
	options_vega_map deribit.private_get_account_summary_response_options_vega_map
);
comment on column deribit.private_get_account_summary_response_options_gamma_map.futures_pl is 'Futures profit and Loss';
comment on column deribit.private_get_account_summary_response_options_gamma_map.currency is 'The selected currency';
comment on column deribit.private_get_account_summary_response_options_gamma_map.options_value is 'Options value';
comment on column deribit.private_get_account_summary_response_options_gamma_map.security_keys_enabled is 'Whether Security Key authentication is enabled (available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_options_gamma_map.self_trading_extended_to_subaccounts is 'true if self trading rejection behavior is applied to trades between subaccounts (available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_options_gamma_map.projected_maintenance_margin is 'Projected maintenance margin';
comment on column deribit.private_get_account_summary_response_options_gamma_map.options_vega is 'Options summary vega';
comment on column deribit.private_get_account_summary_response_options_gamma_map.session_rpl is 'Session realized profit and loss';
comment on column deribit.private_get_account_summary_response_options_gamma_map.has_non_block_chain_equity is 'Optional field returned with value true when user has non block chain equity that is excluded from proof of reserve calculations';
comment on column deribit.private_get_account_summary_response_options_gamma_map.system_name is 'System generated user nickname (available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_options_gamma_map.deposit_address is 'The deposit address for the account (if available)';
comment on column deribit.private_get_account_summary_response_options_gamma_map.futures_session_upl is 'Futures session unrealized profit and Loss';
comment on column deribit.private_get_account_summary_response_options_gamma_map.options_session_upl is 'Options session unrealized profit and Loss';
comment on column deribit.private_get_account_summary_response_options_gamma_map.referrer_id is 'Optional identifier of the referrer (of the affiliation program, and available when parameter extended = true), which link was used by this account at registration. It coincides with suffix of the affiliation link path after /reg-';
comment on column deribit.private_get_account_summary_response_options_gamma_map.options_theta is 'Options summary theta';
comment on column deribit.private_get_account_summary_response_options_gamma_map.login_enabled is 'Whether account is loginable using email and password (available when parameter extended = true and account is a subaccount)';
comment on column deribit.private_get_account_summary_response_options_gamma_map.username is 'Account name (given by user) (available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_options_gamma_map.interuser_transfers_enabled is 'true when the inter-user transfers are enabled for user (available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_options_gamma_map.options_delta is 'Options summary delta';
comment on column deribit.private_get_account_summary_response_options_gamma_map.options_pl is 'Options profit and Loss';
comment on column deribit.private_get_account_summary_response_options_gamma_map.options_vega_map is 'Map of options'' vegas per index';

drop type if exists deribit.private_get_account_summary_response_perpetuals cascade;
create type deribit.private_get_account_summary_response_perpetuals as (
	burst bigint,
	rate bigint,
	type text,
	initial_margin double precision,
	options_gamma_map deribit.private_get_account_summary_response_options_gamma_map
);
comment on column deribit.private_get_account_summary_response_perpetuals.burst is 'Maximal number of perpetual related matching engine requests allowed for user in burst mode';
comment on column deribit.private_get_account_summary_response_perpetuals.rate is 'Number of perpetual related matching engine requests per second allowed for user';
comment on column deribit.private_get_account_summary_response_perpetuals.type is 'Account type (available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_perpetuals.initial_margin is 'The account''s initial margin';
comment on column deribit.private_get_account_summary_response_perpetuals.options_gamma_map is 'Map of options'' gammas per index';

drop type if exists deribit.private_get_account_summary_response_options cascade;
create type deribit.private_get_account_summary_response_options as (
	burst bigint,
	rate bigint,
	perpetuals deribit.private_get_account_summary_response_perpetuals
);
comment on column deribit.private_get_account_summary_response_options.burst is 'Maximal number of options related matching engine requests allowed for user in burst mode';
comment on column deribit.private_get_account_summary_response_options.rate is 'Number of options related matching engine requests per second allowed for user';
comment on column deribit.private_get_account_summary_response_options.perpetuals is 'Field not included if limits for perpetuals are not set.';

drop type if exists deribit.private_get_account_summary_response_non_matching_engine cascade;
create type deribit.private_get_account_summary_response_non_matching_engine as (
	burst bigint,
	rate bigint,
	options deribit.private_get_account_summary_response_options
);
comment on column deribit.private_get_account_summary_response_non_matching_engine.burst is 'Maximal number of non matching engine requests allowed for user in burst mode';
comment on column deribit.private_get_account_summary_response_non_matching_engine.rate is 'Number of non matching engine requests per second allowed for user';
comment on column deribit.private_get_account_summary_response_non_matching_engine.options is 'Field not included if limits for options are not set.';

drop type if exists deribit.private_get_account_summary_response_matching_engine cascade;
create type deribit.private_get_account_summary_response_matching_engine as (
	burst bigint,
	rate bigint,
	non_matching_engine deribit.private_get_account_summary_response_non_matching_engine
);
comment on column deribit.private_get_account_summary_response_matching_engine.burst is 'Maximal number of matching engine requests allowed for user in burst mode';
comment on column deribit.private_get_account_summary_response_matching_engine.rate is 'Number of matching engine requests per second allowed for user';

drop type if exists deribit.private_get_account_summary_response_futures cascade;
create type deribit.private_get_account_summary_response_futures as (
	burst bigint,
	rate bigint,
	matching_engine deribit.private_get_account_summary_response_matching_engine
);
comment on column deribit.private_get_account_summary_response_futures.burst is 'Maximal number of futures related matching engine requests allowed for user in burst mode';
comment on column deribit.private_get_account_summary_response_futures.rate is 'Number of futures related matching engine requests per second allowed for user';

drop type if exists deribit.private_get_account_summary_response_limits cascade;
create type deribit.private_get_account_summary_response_limits as (
	futures deribit.private_get_account_summary_response_futures
);
comment on column deribit.private_get_account_summary_response_limits.futures is 'Field not included if limits for futures are not set.';

drop type if exists deribit.private_get_account_summary_response_fee cascade;
create type deribit.private_get_account_summary_response_fee as (
	currency text,
	fee_type text,
	instrument_type text,
	maker_fee double precision,
	taker_fee double precision,
	limits deribit.private_get_account_summary_response_limits
);
comment on column deribit.private_get_account_summary_response_fee.currency is 'The currency the fee applies to';
comment on column deribit.private_get_account_summary_response_fee.fee_type is 'Fee type - relative if fee is calculated as a fraction of base instrument fee, fixed if fee is calculated solely using user fee';
comment on column deribit.private_get_account_summary_response_fee.instrument_type is 'Type of the instruments the fee applies to - future for future instruments (excluding perpetual), perpetual for future perpetual instruments, option for options';
comment on column deribit.private_get_account_summary_response_fee.maker_fee is 'User fee as a maker';
comment on column deribit.private_get_account_summary_response_fee.taker_fee is 'User fee as a taker';

drop type if exists deribit.private_get_account_summary_response_result cascade;
create type deribit.private_get_account_summary_response_result as (
	maintenance_margin double precision,
	delta_total double precision,
	id bigint,
	options_session_rpl double precision,
	self_trading_reject_mode text,
	futures_session_rpl double precision,
	session_upl double precision,
	fee_balance double precision,
	fees deribit.private_get_account_summary_response_fee[]
);
comment on column deribit.private_get_account_summary_response_result.maintenance_margin is 'The maintenance margin.';
comment on column deribit.private_get_account_summary_response_result.delta_total is 'The sum of position deltas';
comment on column deribit.private_get_account_summary_response_result.id is 'Account id (available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_result.options_session_rpl is 'Options session realized profit and Loss';
comment on column deribit.private_get_account_summary_response_result.self_trading_reject_mode is 'Self trading rejection behavior - reject_taker or cancel_maker (available when parameter extended = true)';
comment on column deribit.private_get_account_summary_response_result.futures_session_rpl is 'Futures session realized profit and Loss';
comment on column deribit.private_get_account_summary_response_result.session_upl is 'Session unrealized profit and loss';
comment on column deribit.private_get_account_summary_response_result.fee_balance is 'The account''s fee balance (it can be used to pay for fees)';
comment on column deribit.private_get_account_summary_response_result.fees is 'User fees in case of any discounts (available when parameter extended = true and user has any discounts)';

drop type if exists deribit.private_get_account_summary_response cascade;
create type deribit.private_get_account_summary_response as (
	id bigint,
	jsonrpc text,
	result deribit.private_get_account_summary_response_result
);
comment on column deribit.private_get_account_summary_response.id is 'The id that was sent in the request';
comment on column deribit.private_get_account_summary_response.jsonrpc is 'The JSON-RPC version (2.0)';

drop type if exists deribit.private_get_account_summary_request_currency cascade;
create type deribit.private_get_account_summary_request_currency as enum ('BTC', 'ETH', 'USDC');

drop type if exists deribit.private_get_account_summary_request cascade;
create type deribit.private_get_account_summary_request as (
	currency deribit.private_get_account_summary_request_currency,
	subaccount_id bigint,
	extended boolean
);
comment on column deribit.private_get_account_summary_request.currency is '(Required) The currency symbol';
comment on column deribit.private_get_account_summary_request.subaccount_id is 'The user id for the subaccount';
comment on column deribit.private_get_account_summary_request.extended is 'Include additional fields';

