/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.private_get_open_orders_by_currency_request_currency cascade;

create type deribit.private_get_open_orders_by_currency_request_currency as enum (
    'BTC',
    'ETH',
    'USDC',
    'USDT'
);

drop type if exists deribit.private_get_open_orders_by_currency_request_kind cascade;

create type deribit.private_get_open_orders_by_currency_request_kind as enum (
    'future',
    'future_combo',
    'option',
    'option_combo',
    'spot'
);

drop type if exists deribit.private_get_open_orders_by_currency_request_type cascade;

create type deribit.private_get_open_orders_by_currency_request_type as enum (
    'all',
    'limit',
    'stop_all',
    'stop_limit',
    'stop_market',
    'take_all',
    'take_limit',
    'take_market',
    'trailing_all',
    'trailing_stop',
    'trigger_all'
);

drop type if exists deribit.private_get_open_orders_by_currency_request cascade;

create type deribit.private_get_open_orders_by_currency_request as (
    currency deribit.private_get_open_orders_by_currency_request_currency,
    kind deribit.private_get_open_orders_by_currency_request_kind,
    type deribit.private_get_open_orders_by_currency_request_type
);

comment on column deribit.private_get_open_orders_by_currency_request.currency is '(Required) The currency symbol';
comment on column deribit.private_get_open_orders_by_currency_request.kind is 'Instrument kind, if not provided instruments of all kinds are considered';
comment on column deribit.private_get_open_orders_by_currency_request.type is 'Order type, default - all';
