/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.private_close_position_request_type cascade;

create type deribit.private_close_position_request_type as enum (
    'limit',
    'market'
);

drop type if exists deribit.private_close_position_request cascade;

create type deribit.private_close_position_request as (
    instrument_name text,
    type deribit.private_close_position_request_type,
    price double precision
);

comment on column deribit.private_close_position_request.instrument_name is '(Required) Instrument name';
comment on column deribit.private_close_position_request.type is '(Required) The order type';
comment on column deribit.private_close_position_request.price is 'Optional price for limit order.';
