/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.private_sell_request_type cascade;

create type deribit.private_sell_request_type as enum (
    'limit',
    'market',
    'market_limit',
    'stop_limit',
    'stop_market',
    'take_limit',
    'take_market',
    'trailing_stop'
);

drop type if exists deribit.private_sell_request_time_in_force cascade;

create type deribit.private_sell_request_time_in_force as enum (
    'fill_or_kill',
    'good_til_cancelled',
    'good_til_day',
    'immediate_or_cancel'
);

drop type if exists deribit.private_sell_request_trigger cascade;

create type deribit.private_sell_request_trigger as enum (
    'index_price',
    'last_price',
    'mark_price'
);

drop type if exists deribit.private_sell_request_advanced cascade;

create type deribit.private_sell_request_advanced as enum (
    'implv',
    'usd'
);

drop type if exists deribit.private_sell_request cascade;

create type deribit.private_sell_request as (
    instrument_name text,
    amount double precision,
    type deribit.private_sell_request_type,
    label text,
    price double precision,
    time_in_force deribit.private_sell_request_time_in_force,
    max_show double precision,
    post_only boolean,
    reject_post_only boolean,
    reduce_only boolean,
    trigger_price double precision,
    trigger_offset double precision,
    trigger deribit.private_sell_request_trigger,
    advanced deribit.private_sell_request_advanced,
    mmp boolean,
    valid_until bigint
);

comment on column deribit.private_sell_request.instrument_name is '(Required) Instrument name';
comment on column deribit.private_sell_request.amount is '(Required) It represents the requested order size. For perpetual and inverse futures the amount is in USD units. For linear futures it is underlying base currency coin. For options it is amount of corresponding cryptocurrency contracts, e.g., BTC or ETH';
comment on column deribit.private_sell_request.type is 'The order type, default: "limit"';
comment on column deribit.private_sell_request.label is 'user defined label for the order (maximum 64 characters)';
comment on column deribit.private_sell_request.price is 'The order price in base currency (Only for limit and stop_limit orders) When adding order with advanced=usd, the field price should be the option price value in USD. When adding order with advanced=implv, the field price should be a value of implied volatility in percentages. For example, price=100, means implied volatility of 100%';
comment on column deribit.private_sell_request.time_in_force is 'Specifies how long the order remains in effect. Default "good_til_cancelled" "good_til_cancelled" - unfilled order remains in order book until cancelled "good_til_day" - unfilled order remains in order book till the end of the trading session "fill_or_kill" - execute a transaction immediately and completely or not at all "immediate_or_cancel" - execute a transaction immediately, and any portion of the order that cannot be immediately filled is cancelled';
comment on column deribit.private_sell_request.max_show is 'Maximum amount within an order to be shown to other customers, 0 for invisible order';
comment on column deribit.private_sell_request.post_only is 'If true, the order is considered post-only. If the new price would cause the order to be filled immediately (as taker), the price will be changed to be just above the spread. Only valid in combination with time_in_force="good_til_cancelled"';
comment on column deribit.private_sell_request.reject_post_only is 'If an order is considered post-only and this field is set to true then the order is put to order book unmodified or request is rejected. Only valid in combination with "post_only" set to true';
comment on column deribit.private_sell_request.reduce_only is 'If true, the order is considered reduce-only which is intended to only reduce a current position';
comment on column deribit.private_sell_request.trigger_price is 'Trigger price, required for trigger orders only (Stop-loss or Take-profit orders)';
comment on column deribit.private_sell_request.trigger_offset is 'The maximum deviation from the price peak beyond which the order will be triggered';
comment on column deribit.private_sell_request.trigger is 'Defines the trigger type. Required for "Stop-Loss", "Take-Profit" and "Trailing" trigger orders';
comment on column deribit.private_sell_request.advanced is 'Advanced option order type. (Only for options)';
comment on column deribit.private_sell_request.mmp is 'Order MMP flag, only for order_type ''limit''';
comment on column deribit.private_sell_request.valid_until is 'Timestamp, when provided server will start processing request in Matching Engine only before given timestamp, in other cases timed_out error will be responded. Remember that the given timestamp should be consistent with the server''s time, use /public/time method to obtain current server time.';
