/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.private_toggle_portfolio_margining_request cascade;

create type deribit.private_toggle_portfolio_margining_request as (
    user_id bigint,
    enabled boolean,
    dry_run boolean
);

comment on column deribit.private_toggle_portfolio_margining_request.user_id is 'Id of a (sub)account - by default current user id is used';
comment on column deribit.private_toggle_portfolio_margining_request.enabled is '(Required) Whether PM or SM should be enabled - PM while true, SM otherwise';
comment on column deribit.private_toggle_portfolio_margining_request.dry_run is 'If true request returns the result without switching the margining model. Default: false';
