/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.public_status_response_result cascade;

create type deribit.public_status_response_result as (
    locked text,
    locked_currencies text[]
);

comment on column deribit.public_status_response_result.locked is 'true when platform is locked in all currencies, partial when some currencies are locked, false - when there are not currencies locked';
comment on column deribit.public_status_response_result.locked_currencies is 'List of currencies in which platform is locked';

drop type if exists deribit.public_status_response cascade;

create type deribit.public_status_response as (
    id bigint,
    jsonrpc text,
    result deribit.public_status_response_result
);

comment on column deribit.public_status_response.id is 'The id that was sent in the request';
comment on column deribit.public_status_response.jsonrpc is 'The JSON-RPC version (2.0)';

