/*
 * AUTO-GENERATED FILE - DO NOT MODIFY
 * 
 * This SQL file was generated by a code generation tool. Any modifications
 * made to this file may be overwritten by subsequent code generation
 * processes and could lead to inconsistencies or errors in the application.
 * 
 * For any required changes, please modify the source templates or the
 * code generation tool's configurations and regenerate this file.
 *
 * WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
 * AND IS STRONGLY DISCOURAGED.
 */
 drop type if exists deribit.public_get_contract_size_response_result cascade;
create type deribit.public_get_contract_size_response_result as (
	contract_size double precision
);
comment on column deribit.public_get_contract_size_response_result.contract_size is 'Contract size, for futures in USD, for options in base currency of the instrument (BTC, ETH, ...)';

drop type if exists deribit.public_get_contract_size_response cascade;
create type deribit.public_get_contract_size_response as (
	id bigint,
	jsonrpc text,
	result deribit.public_get_contract_size_response_result
);
comment on column deribit.public_get_contract_size_response.id is 'The id that was sent in the request';
comment on column deribit.public_get_contract_size_response.jsonrpc is 'The JSON-RPC version (2.0)';

drop type if exists deribit.public_get_contract_size_request cascade;
create type deribit.public_get_contract_size_request as (
	instrument_name text
);
comment on column deribit.public_get_contract_size_request.instrument_name is '(Required) Instrument name';

