/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.public_get_instruments_request_currency cascade;

create type deribit.public_get_instruments_request_currency as enum (
    'BTC',
    'ETH',
    'USDC',
    'USDT'
);

drop type if exists deribit.public_get_instruments_request_kind cascade;

create type deribit.public_get_instruments_request_kind as enum (
    'future',
    'future_combo',
    'option',
    'option_combo',
    'spot'
);

drop type if exists deribit.public_get_instruments_request cascade;

create type deribit.public_get_instruments_request as (
    currency deribit.public_get_instruments_request_currency,
    kind deribit.public_get_instruments_request_kind,
    expired boolean
);

comment on column deribit.public_get_instruments_request.currency is '(Required) The currency symbol';
comment on column deribit.public_get_instruments_request.kind is 'Instrument kind, if not provided instruments of all kinds are considered';
comment on column deribit.public_get_instruments_request.expired is 'Set to true to show recently expired instruments instead of active ones.';
