/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.public_get_index_response_result cascade;

create type deribit.public_get_index_response_result as (
    BTC double precision,
    ETH double precision,
    edp double precision
);

comment on column deribit.public_get_index_response_result.BTC is 'The current index price for BTC-USD (only for selected currency == BTC)';
comment on column deribit.public_get_index_response_result.ETH is 'The current index price for ETH-USD (only for selected currency == ETH)';
comment on column deribit.public_get_index_response_result.edp is 'Estimated delivery price for the currency. For more details, see Documentation > General > Expiration Price';

drop type if exists deribit.public_get_index_response cascade;

create type deribit.public_get_index_response as (
    id bigint,
    jsonrpc text,
    result deribit.public_get_index_response_result
);

comment on column deribit.public_get_index_response.id is 'The id that was sent in the request';
comment on column deribit.public_get_index_response.jsonrpc is 'The JSON-RPC version (2.0)';

