/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.public_get_delivery_prices_response_datum cascade;

create type deribit.public_get_delivery_prices_response_datum as (
    date text,
    delivery_price double precision
);

comment on column deribit.public_get_delivery_prices_response_datum.date is 'The event date with year, month and day';
comment on column deribit.public_get_delivery_prices_response_datum.delivery_price is 'The settlement price for the instrument. Only when state = closed';

drop type if exists deribit.public_get_delivery_prices_response_result cascade;

create type deribit.public_get_delivery_prices_response_result as (
    data deribit.public_get_delivery_prices_response_datum[],
    records_total double precision
);

comment on column deribit.public_get_delivery_prices_response_result.records_total is 'Available delivery prices';

drop type if exists deribit.public_get_delivery_prices_response cascade;

create type deribit.public_get_delivery_prices_response as (
    id bigint,
    jsonrpc text,
    result deribit.public_get_delivery_prices_response_result
);

comment on column deribit.public_get_delivery_prices_response.id is 'The id that was sent in the request';
comment on column deribit.public_get_delivery_prices_response.jsonrpc is 'The JSON-RPC version (2.0)';

