/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.public_get_currencies_response_withdrawal_priority cascade;

create type deribit.public_get_currencies_response_withdrawal_priority as (
    name text,
    value double precision
);



drop type if exists deribit.public_get_currencies_response_result cascade;

create type deribit.public_get_currencies_response_result as (
    coin_type text,
    currency text,
    currency_long text,
    fee_precision bigint,
    min_confirmations bigint,
    min_withdrawal_fee double precision,
    withdrawal_fee double precision,
    withdrawal_priorities deribit.public_get_currencies_response_withdrawal_priority[]
);

comment on column deribit.public_get_currencies_response_result.coin_type is 'The type of the currency.';
comment on column deribit.public_get_currencies_response_result.currency is 'The abbreviation of the currency. This abbreviation is used elsewhere in the API to identify the currency.';
comment on column deribit.public_get_currencies_response_result.currency_long is 'The full name for the currency.';
comment on column deribit.public_get_currencies_response_result.fee_precision is 'fee precision';
comment on column deribit.public_get_currencies_response_result.min_confirmations is 'Minimum number of block chain confirmations before deposit is accepted.';
comment on column deribit.public_get_currencies_response_result.min_withdrawal_fee is 'The minimum transaction fee paid for withdrawals';
comment on column deribit.public_get_currencies_response_result.withdrawal_fee is 'The total transaction fee paid for withdrawals';

drop type if exists deribit.public_get_currencies_response cascade;

create type deribit.public_get_currencies_response as (
    id bigint,
    jsonrpc text,
    result deribit.public_get_currencies_response_result[]
);

comment on column deribit.public_get_currencies_response.id is 'The id that was sent in the request';
comment on column deribit.public_get_currencies_response.jsonrpc is 'The JSON-RPC version (2.0)';

