/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.public_get_order_book_by_instrument_id_request_depth cascade;

create type deribit.public_get_order_book_by_instrument_id_request_depth as enum (
    '1',
    '10',
    '100',
    '1000',
    '10000',
    '20',
    '5',
    '50'
);

drop type if exists deribit.public_get_order_book_by_instrument_id_request cascade;

create type deribit.public_get_order_book_by_instrument_id_request as (
    instrument_id bigint,
    depth deribit.public_get_order_book_by_instrument_id_request_depth
);

comment on column deribit.public_get_order_book_by_instrument_id_request.instrument_id is '(Required) The instrument ID for which to retrieve the order book, see public/get_instruments to obtain instrument IDs.';
comment on column deribit.public_get_order_book_by_instrument_id_request.depth is 'The number of entries to return for bids and asks.';
