/*
* AUTO-GENERATED FILE - DO NOT MODIFY
*
* This SQL file was generated by a code generation tool. Any modifications
* made to this file may be overwritten by subsequent code generation
* processes and could lead to inconsistencies or errors in the application.
*
* For any required changes, please modify the source templates or the
* code generation tool's configurations and regenerate this file.
*
* WARNING: MODIFYING THIS FILE DIRECTLY CAN LEAD TO UNEXPECTED BEHAVIOR
* AND IS STRONGLY DISCOURAGED.
*/
drop type if exists deribit.public_get_rfqs_response_result cascade;

create type deribit.public_get_rfqs_response_result as (
    amount double precision,
    instrument_name text,
    last_rfq_timestamp bigint,
    side text,
    traded_volume double precision
);

comment on column deribit.public_get_rfqs_response_result.amount is 'It represents the requested order size. For perpetual and futures the amount is in USD units, for options it is amount of corresponding cryptocurrency contracts, e.g., BTC or ETH.';
comment on column deribit.public_get_rfqs_response_result.instrument_name is 'Unique instrument identifier';
comment on column deribit.public_get_rfqs_response_result.last_rfq_timestamp is 'The timestamp of last RFQ (milliseconds since the Unix epoch)';
comment on column deribit.public_get_rfqs_response_result.side is 'Side - buy or sell';
comment on column deribit.public_get_rfqs_response_result.traded_volume is 'Volume traded since last RFQ';

drop type if exists deribit.public_get_rfqs_response cascade;

create type deribit.public_get_rfqs_response as (
    id bigint,
    jsonrpc text,
    result deribit.public_get_rfqs_response_result[]
);

comment on column deribit.public_get_rfqs_response.id is 'The id that was sent in the request';
comment on column deribit.public_get_rfqs_response.jsonrpc is 'The JSON-RPC version (2.0)';

